In [1]:
import pandas as pd
import re

In [2]:
def tem_caracter_chines(texto):
    # Regex para caracteres chineses (CJK Unified Ideographs)
    padrao = r'[\u4e00-\u9fff]'
    return bool(re.search(padrao, texto))

In [3]:
path = 'data/treat/dedup2_result_scraper_wikiaves_udi.json'
df = pd.read_json(path)
df

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico,bico,asa,pata,tipo
0,Rhea americana,Rheiformes,Rheidae,None,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista,NaN,NaN,NaN,NaN
1,Crypturellus undulatus,Tinamiformes,Tinamidae,None,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",None,None,[diurna],generalista,NaN,NaN,NaN,NaN
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,None,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",None,None,"[diurna, crepuscular]",sondador,NaN,NaN,NaN,NaN
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,None,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador,NaN,NaN,NaN,NaN
4,Nothura maculosa,Tinamiformes,Tinamidae,None,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,"[frutos, sementes, flores, insetos]","[cerrado, caatinga, campo natural, área urbana]",,territorial,[],None,Frugívoro,,,onívoro
366,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,"[sementes, frutas]","[caatinga, cerrado]",voadora,None,[diurna],generalista,NaN,NaN,NaN,NaN
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,"[frutas, sementes, insectos]","[mata ciliar, zona de cultivo, mato aberto, ár...",voadora,gregária,[diurna],generalista,NaN,NaN,NaN,NaN
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,"[insetos, néctar, frutos]","[área urbana, floresta aberta, campo natural]",voadora,gregária,[diurna],generalista,NaN,NaN,NaN,NaN
369,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,"[insetos, frutos]","[mata ciliar, caATINGa, campo natural, plantaç...",voadora,gregária,[diurna],None,Frugívoro,Alto coeficiente de proporcionalidade,Anizodáctilo,frugívoro

In [4]:
df['contem_chines'] = df['resumo_llm'].apply(tem_caracter_chines)
df[df['contem_chines'] == True]["resumo_llm"]

Series([], Name: resumo_llm, dtype: object)

In [5]:
df["tamanho"].unique()

array(['grande', 'media', None, 'pequena', 'Pequeno', 'Médio', 'Grande',
       ''], dtype=object)

In [6]:
df.loc[df["tamanho"]=='Grande','tamanho'] = 'grande'
df.loc[df["tamanho"]=='Médio','tamanho'] = 'media'
df.loc[df["tamanho"]=='médio','tamanho'] = 'media'
df.loc[df["tamanho"]=='Pequeno','tamanho'] = 'pequena'
df.loc[df["tamanho"]=='pequeno','tamanho'] = 'pequena'

In [7]:
df["tipo_bico"].unique()

array(['generalista', 'sondador', None, 'filtrador', 'frugivoro',
       'granivoro', 'insetivoro', 'nectarivoro', 'insetos em troncos',
       'limicola', 'pescador', 'carniceiro', 'raptorial'], dtype=object)

In [8]:
new_df = df[[
    'taxonomia', 'ordem', 'familia', 'genero', 'especie',
    'nome_pt', 'nome_eng', 'url_wikiaves', 'url_image', 'resumo_llm',
    'tamanho', 'tipo_bico', 'cores', 'habitat','dieta_principal',
    'atividade'
]]
new_df

,taxonomia,ordem,familia,genero,especie,nome_pt,nome_eng,url_wikiaves,url_image,resumo_llm,tamanho,tipo_bico,cores,habitat,dieta_principal,atividade
0,Rhea americana,Rheiformes,Rheidae,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,https://s3.amazonaws.com/media.wikiaves.com.br...,"A ema (Rhea americana) é uma ave ratita, a mai...",grande,generalista,"[cinza, preto, amarelado]","[campo natural, cerrado, pampa]","[folhas, frutas, sementes, insetos, moluscos, ...","[diurna, crepuscular]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Crypturellus undulatus, conhecida co...",media,generalista,[],"[mata ciliar, cerrado]","[frutas, moluscos, insetos]",[diurna]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,https://s3.amazonaws.com/media.wikiaves.com.br...,"Crypturellus parvirostris, conhecido como inha...",None,sondador,"[marrom avermelhado, acinzentado]","[cerrado, campo natural, plantação, pastagem]","[sementes, insetos, vermes]","[diurna, crepuscular]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,https://s3.amazonaws.com/media.wikiaves.com.br...,"Rhynchotus rufescens, uma ave terrícola da fam...",media,sondador,"[preto, bege, marrom escuro, canela, castanho ...","[campo natural, cerrado, caatinga]","[insetos, sementes, raízes, tubérculos, roedores]",[diurna]
4,Nothura maculosa,Tinamiformes,Tinamidae,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Nothura maculosa* é uma ave de pequ...,pequena,None,"[marrons, amarelo, branco]","[campo natural, plantação, área urbana]","[grãos, artrópodes, moluscos, frutas]",[diurna]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Schistochlamys ruficapillus, também ...",pequena,None,"[azul-acinzentada, negra, acanelado, branco-ac...","[cerrado, caatinga, campo natural, área urbana]","[frutos, sementes, flores, insetos]",[]
366,Paroaria dominicana,Passeriformes,Thraupidae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Paroaria dominicana, com uma comprimento de ...",media,generalista,"[vermelho, cinza, preto, branco, pardo]","[caatinga, cerrado]","[sementes, frutas]",[diurna]
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis sayaca, também conhecida como sayac...",pequena,generalista,"[cinza, azul turquesa, esverdeado, branco]","[mata ciliar, zona de cultivo, mato aberto, ár...","[frutas, sementes, insectos]",[diurna]
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis palmarum, conhecida como sanhaço-do...",media,generalista,"[esverdeada, amarelada]","[área urbana, floresta aberta, campo natural]","[insetos, néctar, frutos]",[diurna]
369,Stilpnia cayana,Passeriformes,Thraupidae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Stilpnia cayana* é uma ave que apre...,media,None,"[amarelo-dourada, amarelo, preto, negra]","[mata ciliar, caATINGa, campo natural, plantaç...","[insetos, frutos]",[diurna]

In [9]:
path = "data/treat/especies_uberlandia.csv"
df_registro = pd.read_csv(path)
df_registro

,Espécie,Nome Comum,Sons,Fotos
0,emaRhea americana,ema,0,21
1,jaóCrypturellus undulatus,jaó,2,6
2,inhambu-chororóCrypturellus parvirostris,inhambu-chororó,5,11
3,perdizRhynchotus rufescens,perdiz,2,2
4,codorna-amarelaNothura maculosa,codorna-amarela,2,17
...,...,...,...,...
366,bico-de-veludoSchistochlamys ruficapillus,bico-de-veludo,2,9
367,cardeal-do-nordesteParoaria dominicana,cardeal-do-nordeste,0,13
368,sanhaço-cinzentoThraupis sayaca,sanhaço-cinzento,2,34
369,sanhaço-do-coqueiroThraupis palmarum,sanhaço-do-coqueiro,1,43
370,saíra-amarelaStilpnia cayana,saíra-amarela,0,58

In [10]:
df_registro["qtd_registros"] = df_registro["Fotos"] + df_registro["Sons"]

In [11]:
new_df = new_df.merge(
    df_registro[['Nome Comum',"qtd_registros"]],
    left_on='nome_pt',right_on="Nome Comum", how='left')
new_df

,taxonomia,ordem,familia,genero,especie,nome_pt,nome_eng,url_wikiaves,url_image,resumo_llm,tamanho,tipo_bico,cores,habitat,dieta_principal,atividade,Nome Comum,qtd_registros
0,Rhea americana,Rheiformes,Rheidae,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,https://s3.amazonaws.com/media.wikiaves.com.br...,"A ema (Rhea americana) é uma ave ratita, a mai...",grande,generalista,"[cinza, preto, amarelado]","[campo natural, cerrado, pampa]","[folhas, frutas, sementes, insetos, moluscos, ...","[diurna, crepuscular]",ema,21.0
1,Crypturellus undulatus,Tinamiformes,Tinamidae,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Crypturellus undulatus, conhecida co...",media,generalista,[],"[mata ciliar, cerrado]","[frutas, moluscos, insetos]",[diurna],jaó,8.0
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,https://s3.amazonaws.com/media.wikiaves.com.br...,"Crypturellus parvirostris, conhecido como inha...",None,sondador,"[marrom avermelhado, acinzentado]","[cerrado, campo natural, plantação, pastagem]","[sementes, insetos, vermes]","[diurna, crepuscular]",inhambu-chororó,16.0
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,https://s3.amazonaws.com/media.wikiaves.com.br...,"Rhynchotus rufescens, uma ave terrícola da fam...",media,sondador,"[preto, bege, marrom escuro, canela, castanho ...","[campo natural, cerrado, caatinga]","[insetos, sementes, raízes, tubérculos, roedores]",[diurna],perdiz,4.0
4,Nothura maculosa,Tinamiformes,Tinamidae,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Nothura maculosa* é uma ave de pequ...,pequena,None,"[marrons, amarelo, branco]","[campo natural, plantação, área urbana]","[grãos, artrópodes, moluscos, frutas]",[diurna],codorna-amarela,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Schistochlamys ruficapillus, também ...",pequena,None,"[azul-acinzentada, negra, acanelado, branco-ac...","[cerrado, caatinga, campo natural, área urbana]","[frutos, sementes, flores, insetos]",[],bico-de-veludo,11.0
366,Paroaria dominicana,Passeriformes,Thraupidae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Paroaria dominicana, com uma comprimento de ...",media,generalista,"[vermelho, cinza, preto, branco, pardo]","[caatinga, cerrado]","[sementes, frutas]",[diurna],cardeal-do-nordeste,13.0
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis sayaca, também conhecida como sayac...",pequena,generalista,"[cinza, azul turquesa, esverdeado, branco]","[mata ciliar, zona de cultivo, mato aberto, ár...","[frutas, sementes, insectos]",[diurna],sanhaço-cinzento,36.0
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis palmarum, conhecida como sanhaço-do...",media,generalista,"[esverdeada, amarelada]","[área urbana, floresta aberta, campo natural]","[insetos, néctar, frutos]",[diurna],sanhaço-do-coqueiro,44.0
369,Stilpnia cayana,Passeriformes,Thraupidae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Stilpnia cayana* é uma ave que apre...,media,None,"[amarelo-dourada, amarelo, preto, negra]","[mata ciliar, caATINGa, campo natural, plantaç...","[insetos, frutos]",[diurna],saíra-amarela,58.0

In [12]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   taxonomia        370 non-null    object
 1   ordem            370 non-null    object
 2   familia          370 non-null    object
 3   genero           370 non-null    object
 4   especie          370 non-null    object
 5   nome_pt          370 non-null    object
 6   nome_eng         370 non-null    object
 7   url_wikiaves     370 non-null    object
 8   url_image        369 non-null    object
 9   resumo_llm       370 non-null    object
 10  tamanho          352 non-null    object
 11  tipo_bico        275 non-null    object
 12  cores            370 non-null    object
 13  habitat          369 non-null    object
 14  dieta_principal  369 non-null    object
 15  atividade        370 non-null    object
 16  Nome Comum       369 non-null    object
 17  qtd_registros    369 non-null    float64
dtypes: float64(1), object(17)
memory usage: 52.2+ KB

In [13]:
new_df.drop(columns=['Nome Comum'], inplace=True)

In [14]:
print(df_registro.columns)
print(new_df.columns)

Index(['Espécie', 'Nome Comum', 'Sons', 'Fotos', 'qtd_registros'], dtype='object')
Index(['taxonomia', 'ordem', 'familia', 'genero', 'especie', 'nome_pt',
       'nome_eng', 'url_wikiaves', 'url_image', 'resumo_llm', 'tamanho',
       'tipo_bico', 'cores', 'habitat', 'dieta_principal', 'atividade',
       'qtd_registros'],
      dtype='object')

In [15]:
new_df['frequencia_normalizada'] = new_df['qtd_registros'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
new_df

,taxonomia,ordem,familia,genero,especie,nome_pt,nome_eng,url_wikiaves,url_image,resumo_llm,tamanho,tipo_bico,cores,habitat,dieta_principal,atividade,qtd_registros,frequencia_normalizada
0,Rhea americana,Rheiformes,Rheidae,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,https://s3.amazonaws.com/media.wikiaves.com.br...,"A ema (Rhea americana) é uma ave ratita, a mai...",grande,generalista,"[cinza, preto, amarelado]","[campo natural, cerrado, pampa]","[folhas, frutas, sementes, insetos, moluscos, ...","[diurna, crepuscular]",21.0,0.130719
1,Crypturellus undulatus,Tinamiformes,Tinamidae,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Crypturellus undulatus, conhecida co...",media,generalista,[],"[mata ciliar, cerrado]","[frutas, moluscos, insetos]",[diurna],8.0,0.045752
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,https://s3.amazonaws.com/media.wikiaves.com.br...,"Crypturellus parvirostris, conhecido como inha...",None,sondador,"[marrom avermelhado, acinzentado]","[cerrado, campo natural, plantação, pastagem]","[sementes, insetos, vermes]","[diurna, crepuscular]",16.0,0.098039
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,https://s3.amazonaws.com/media.wikiaves.com.br...,"Rhynchotus rufescens, uma ave terrícola da fam...",media,sondador,"[preto, bege, marrom escuro, canela, castanho ...","[campo natural, cerrado, caatinga]","[insetos, sementes, raízes, tubérculos, roedores]",[diurna],4.0,0.019608
4,Nothura maculosa,Tinamiformes,Tinamidae,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Nothura maculosa* é uma ave de pequ...,pequena,None,"[marrons, amarelo, branco]","[campo natural, plantação, área urbana]","[grãos, artrópodes, moluscos, frutas]",[diurna],19.0,0.117647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Schistochlamys ruficapillus, também ...",pequena,None,"[azul-acinzentada, negra, acanelado, branco-ac...","[cerrado, caatinga, campo natural, área urbana]","[frutos, sementes, flores, insetos]",[],11.0,0.065359
366,Paroaria dominicana,Passeriformes,Thraupidae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Paroaria dominicana, com uma comprimento de ...",media,generalista,"[vermelho, cinza, preto, branco, pardo]","[caatinga, cerrado]","[sementes, frutas]",[diurna],13.0,0.078431
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis sayaca, também conhecida como sayac...",pequena,generalista,"[cinza, azul turquesa, esverdeado, branco]","[mata ciliar, zona de cultivo, mato aberto, ár...","[frutas, sementes, insectos]",[diurna],36.0,0.228758
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A Thraupis palmarum, conhecida como sanhaço-do...",media,generalista,"[esverdeada, amarelada]","[área urbana, floresta aberta, campo natural]","[insetos, néctar, frutos]",[diurna],44.0,0.281046
369,Stilpnia cayana,Passeriformes,Thraupidae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Stilpnia cayana* é uma ave que apre...,media,None,"[amarelo-dourada, amarelo, preto, negra]","[mata ciliar, caATINGa, campo natural, plantaç...","[insetos, frutos]",[diurna],58.0,0.372549

In [16]:
new_df.to_json("oficial_dataset_udi.json", orient="records")