In [1]:
import pandas as pd
import numpy as np

import json
import ast
import re

In [2]:
path_json = "result_llm_wikiaves_udi.json"
df = pd.read_json(path_json)
df.head()

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN

In [3]:
def string_to_dict(string_input):
    try:
        match = re.search(r'```json\s*(.*?)\s*```', string_input, re.DOTALL)

        content = match.group(1)

        string_clean = re.sub(r'^```json\n|\n```$','',content.strip())
        string_clean = string_clean.replace('\\','')
        string_clean = string_clean.replace('...','')

        try:
            string_json = json.loads(string_clean)
        except json.JSONDecodeError:
            string_json = ast.literal_eval(string_clean)
        
        return string_json
    except:
        return {}

In [4]:
examples_string = [
    "```json\n{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}\n```",
    "```json\n{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': [\"negro\", \"branco\", \"creme-acinzentada\"], 'tamanho': 'Grande'} \n```",
    "```json\n{'habitat': []}\n```",
    "```json\n{'locomocao': '...', 'sociabilidade': '...', 'atividade': ['noturna']}\n```",
    "```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "
]

In [5]:
for example in examples_string:
    format = string_to_dict(example)
    print(format)

{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}
{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': ['negro', 'branco', 'creme-acinzentada'], 'tamanho': 'Grande'}
{'habitat': []}
{'locomocao': '', 'sociabilidade': '', 'atividade': ['noturna']}
{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}

In [6]:
array_mor = df["morfologia_llm"]
array_mor = array_mor.dropna()
array_mor

0      ```json\n{'bico': 'Generalista', 'asa': 'Elípt...
1      ```json\n{'bico': 'Generalista', 'asa': '', 'p...
2      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
3      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
4      ```json\n{'bico': '', 'asa': '', 'pata': '', '...
                             ...
735    ```json\n{'bico': 'Generalista', 'asa': '', 'p...
736    ```json\n{'bico': 'Granívoro', 'asa': '', 'pat...
737    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
738    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
739    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
Name: morfologia_llm, Length: 740, dtype: object

In [7]:
array_mor[array_mor.str.contains('ariatric')]
array_mor[41]

"```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "

In [8]:
array_mor.map(string_to_dict)

0      {'bico': 'Generalista', 'asa': 'Elíptica', 'pa...
1      {'bico': 'Generalista', 'asa': '', 'pata': '',...
2      {'bico': 'Sondador', 'asa': '', 'pata': '', 'c...
3      {'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...
4      {'bico': '', 'asa': '', 'pata': '', 'cores': [...
                             ...
735    {'bico': 'Generalista', 'asa': '', 'pata': '',...
736    {'bico': 'Granívoro', 'asa': '', 'pata': '', '...
737    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
738    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
739    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
Name: morfologia_llm, Length: 740, dtype: object

In [9]:
df["morfologia_llm_json"] = df["morfologia_llm"].map(string_to_dict)
df["food_llm_json"] = df["food_llm"].map(string_to_dict)
df["habitat_llm_json"] = df["habitat_llm"].map(string_to_dict)
df["behavior_llm_json"] = df["behavior_llm"].map(string_to_dict)
df

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,...,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g..."
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,...,"Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid..."
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid..."
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,...,Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's..."
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,...,"Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,NaN,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,...,"No Brasil, ocorre nos estados do Maranhão, Par...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'caatinga', '...","```json\n{'locomocao': '...', 'sociabilidade':...",3682.0,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['sementes', 'fru...","{'habitat': ['cerrado', 'caatinga', 'campo nat...","{'locomocao': '', 'sociabilidade': 'territoria..."
736,NaN,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,...,Ocorre especialmente nas regiões Nordeste e Su...,"```json\n{'bico': 'Granívoro', 'asa': '', 'pat...","```json\n{'tipo': 'granívoro', 'itens': ['seme...","```json\n{'habitat': ['caatinga', 'cerrado']}\...","```json\n{'locomocao': 'voadora', 'sociabilida...",3684.0,"{'bico': 'Granívoro', 'asa': '', 'pata': '', '...","{'tipo': 'granívoro', 'itens': ['sementes', 'f...","{'habitat': ['caatinga', 'cerrado']}","{'locomocao': 'voadora', 'sociabilidade': '', ..."
737,NaN,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,...,Ocorre nas regiões tropicais e subtropicais ao...,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['capoe', 'mata ciliar', ...","```json\n{'locomocao': 'voadora', 'sociabilida...",3695.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoe', 'mata ciliar', 'zona de ...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
738,NaN,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,...,Ocorre em todo o Brasil e também na América Ce...,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'flores...","```json\n{'locomocao': 'voadora', 'sociabilida...",3697.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['insetos', 'frut...","{'habitat': ['campo natural', 'floresta aberta...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
739,NaN,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,...,A espécie é dividida em dois grupos:,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['capoeira', 'área ciliar...","```json\n{'locomocao': '', 'sociabilidade': 'g...",3704.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoeira', 'área ciliar', 'área ...","{'locomocao': '', 'sociabilidade': 'gregária',..."

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0                        158 non-null    float64
 1   taxonomia            740 non-null    object
 2   ordem                740 non-null    object
 3   familia              740 non-null    object
 4   subfamilia           578 non-null    object
 5   genero               740 non-null    object
 6   especie              740 non-null    object
 7   nome_pt              740 non-null    object
 8   nome_eng             740 non-null    object
 9   url_wikiaves         740 non-null    object
 10  caracteristicas      739 non-null    object
 11  alimentacao          737 non-null    object
 12  reproducao           739 non-null    object
 13  habitos              737 non-null    object
 14  dist_geo             735 non-null    object
 15  morfologia_llm       740 non-null    object
 16  food_llm             740 non-null    object
 17  habitat_llm          740 non-null    object
 18  behavior_llm         740 non-null    object
 19  Unnamed: 0           582 non-null    float64
 20  morfologia_llm_json  740 non-null    object
 21  food_llm_json        740 non-null    object
 22  habitat_llm_json     740 non-null    object
 23  behavior_llm_json    740 non-null    object
dtypes: float64(2), object(22)
memory usage: 138.9+ KB

In [11]:
new_df = df[
    [
        'taxonomia', 'ordem', 'familia','subfamilia','genero',
        'especie','nome_pt','nome_eng','url_wikiaves','caracteristicas',
        'alimentacao','reproducao','habitos','dist_geo',
        'morfologia_llm_json','food_llm_json','habitat_llm_json','behavior_llm_json'
    ]
]
new_df

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g..."
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid..."
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid..."
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's..."
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,"Granívoro. Alimenta-se também de frutos, algum...",Ocorrem 2 ou 3 posturas por temporada. Põe 2 o...,"Pode ser encontrado em cerrados, caatingas, ca...","No Brasil, ocorre nos estados do Maranhão, Par...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['sementes', 'fru...","{'habitat': ['cerrado', 'caatinga', 'campo nat...","{'locomocao': '', 'sociabilidade': 'territoria..."
736,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",Predominantemente granívoro com adaptação para...,Durante a reprodução vive estritamente aos cas...,Habita mata baixa rala e bem ensolarada (caati...,Ocorre especialmente nas regiões Nordeste e Su...,"{'bico': 'Granívoro', 'asa': '', 'pata': '', '...","{'tipo': 'granívoro', 'itens': ['sementes', 'f...","{'habitat': ['caatinga', 'cerrado']}","{'locomocao': 'voadora', 'sociabilidade': '', ..."
737,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,"Frutos, costuma consumir muito o fruto da aroe...","O ninho, construído pelo casal, é compacto, fe...","Habita matas abertas, capões, matas ciliares, ...",Ocorre nas regiões tropicais e subtropicais ao...,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoe', 'mata ciliar', 'zona de ...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
738,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,"Caça insetos no meio das folhas, às vezes fica...",Possui um chamado de notas agudas e assobiadas...,"Muito ativo, vive em casais e pequenos grupos,...",Ocorre em todo o Brasil e também na América Ce...,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['insetos', 'frut...","{'habitat': ['campo natural', 'floresta aberta...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
739,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,Essa saíra se alimenta de frutos e insetos com...,"O ninho, em forma de taça aberta, é feito com ...","Habita capoeiras, matas abertas e ciliares, ár...",A espécie é dividida em dois grupos:,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoeira', 'área ciliar', 'área ...","{'locomocao': '', 'sociabilidade': 'gregária',..."

In [12]:
new_df['tipo_bico'] = new_df['morfologia_llm_json'].map(lambda x: x.get('bico', None))
new_df['formato_asa'] = new_df['morfologia_llm_json'].map(lambda x: x.get('asa', None))
new_df['tipo_pata'] = new_df['morfologia_llm_json'].map(lambda x: x.get('pata', None))
new_df['cores'] = new_df['morfologia_llm_json'].map(lambda x: x.get('cores', None))
new_df.head()

/tmp/ipykernel_7079/2316315217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tipo_bico'] = new_df['morfologia_llm_json'].map(lambda x: x.get('bico', None))
/tmp/ipykernel_7079/2316315217.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['formato_asa'] = new_df['morfologia_llm_json'].map(lambda x: x.get('asa', None))
/tmp/ipykernel_7079/2316315217.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tipo_pata'] = new_df['morfologia_llm_json'].map(lambda x: x.get('pata', None))
/tmp/ipykernel_7079/2316315217.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cores'] = new_df['morfologia_llm_json'].map(lambda x: x.get('cores', None))

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,habitos,dist_geo,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ..."
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]"

In [13]:
new_df['caracteristica_trofica'] = new_df['food_llm_json'].map(lambda x: x.get('tipo', None))
new_df['dieta_principal'] = new_df['food_llm_json'].map(lambda x: x.get('itens', None))
new_df.head()

/tmp/ipykernel_7079/3063555259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['caracteristica_trofica'] = new_df['food_llm_json'].map(lambda x: x.get('tipo', None))

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores,caracteristica_trofica,dieta_principal
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",onívoro,"[folhas, frutas, sementes, insetos, moluscos, ..."
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[],onívoro,"[frutas, moluscos, insetos]"
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]",onívoro,"[sementes, insetos, vermes]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",onívoro,"[insetos, sementes, raízes, tubérculos, roedores]"
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]",onívoro,"[grãos, artrópodes, moluscos, frutas]"

In [14]:
new_df['habitat'] = new_df['habitat_llm_json'].map(lambda x: x.get('habitat', None))
new_df.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,food_llm_json,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores,caracteristica_trofica,dieta_principal,habitat
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[],onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]"
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]",onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]"
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]",onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]"

In [15]:
new_df['locomocao'] = new_df['behavior_llm_json'].map(lambda x: x.get('locomocao', None))
new_df['sociabilidade'] = new_df['behavior_llm_json'].map(lambda x: x.get('sociabilidade', None))
new_df['atividade'] = new_df['behavior_llm_json'].map(lambda x: x.get('atividade', None))
new_df.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_bico,formato_asa,tipo_pata,cores,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,Generalista,,,[],onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,Sondador,,,"[marrom avermelhado, acinzentado]",onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna]
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,,,,"[marrons, amarelo, branco]",onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna]

In [16]:
df_graph = new_df.dropna()
df_graph.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_bico,formato_asa,tipo_pata,cores,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,Generalista,,,[],onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,Sondador,,,"[marrom avermelhado, acinzentado]",onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna]
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,,,,"[marrons, amarelo, branco]",onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna]

In [17]:
bico_by_familly = {
    "Generalista": ["Turdidae", "Thraupidae", "Mimidae"],
    "Insetívoro": ["Tyrannidae", "Troglodytidae", "Furnariidae"],
    "Granívoro": ["Fringillidae", "Emberizidae", "Cardinalidae"],
    "Comedor de sementes de pinho": [],
    "Nectívoro": ["Trochilidae", "Meliphagidae"],
    "Frugívoro": ["Ramphastidae", "Psittacidae", "Cotingidae"],
    "Insetos em troncos": ["Picidae"],
    "Rede de pesca": ["Sulidae"],
    "Pescador de superfície": ["Laridae", "Sternidae"],
    "Limícola": ["Scolopacidae", "Charadriidae"],
    "Sondador": ["Recurvirostridae", "Ibidorhynchidae"],
    "Filtrador": ["Phoenicopteridae", "Anatidae"],
    "Pescador": ["Alcedinidae", "Anhingidae"],
    "Pato mergulhador": ["Anatidae"],
    "Carniceiro": ["Cathartidae"],
    "Raptorial": ["Accipitridae", "Falconidae"]
}


def recap_bico_by_familly(familly: str):
    for key, values in bico_by_familly.items():
        if familly in values:
            return key
    return None

In [18]:
df_graph["tipo_bico_recap"] = df_graph["familia"].apply(recap_bico_by_familly)
df_graph["tipo_bico_recap"]

/tmp/ipykernel_7079/3831557202.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_graph["tipo_bico_recap"] = df_graph["familia"].apply(recap_bico_by_familly)

0             None
1             None
2             None
3             None
4             None
          ...
735    Generalista
736    Generalista
737    Generalista
738    Generalista
739    Generalista
Name: tipo_bico_recap, Length: 564, dtype: object

In [19]:
df_graph[df_graph["tipo_bico_recap"].isna()]["familia"].unique()

array(['Rheidae', 'Tinamidae', 'Anhimidae', 'Cracidae', 'Podicipedidae',
       'Columbidae', 'Cuculidae', 'Nyctibiidae', 'Caprimulgidae',
       'Apodidae', 'Aramidae', 'Rallidae', 'Heliornithidae', 'Jacanidae',
       'Ciconiidae', 'Phalacrocoracidae', 'Ardeidae', 'Threskiornithidae',
       'Pandionidae', 'Tytonidae', 'Strigidae', 'Trogonidae', 'Momotidae',
       'Galbulidae', 'Bucconidae', 'Cariamidae', 'Thamnophilidae',
       'Dendrocolaptidae', 'Pipridae', 'Tityridae', 'Rhynchocyclidae',
       'Icteridae'], dtype=object)

In [20]:
df_graph.to_json("parameterized_dataset_udi.json")