In [1]:
import pandas as pd

import json
import ast
import re

In [2]:
path_json = "result_llm_wikiaves_udi.json"
df = pd.read_json(path_json)
df.head()

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN

In [44]:
def string_to_dict(string_input):
    try:
        match = re.search(r'```json\s*(.*?)\s*```', string_input, re.DOTALL)

        content = match.group(1)

        string_clean = re.sub(r'^```json\n|\n```$','',content.strip())
        string_clean = string_clean.replace('\\','')
        string_clean = string_clean.replace('...','')

        try:
            string_json = json.loads(string_clean)
        except json.JSONDecodeError:
            string_json = ast.literal_eval(string_clean)
        
        return string_json
    except:
        return {}

In [45]:
examples_string = [
    "```json\n{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}\n```",
    "```json\n{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': [\"negro\", \"branco\", \"creme-acinzentada\"], 'tamanho': 'Grande'} \n```",
    "```json\n{'habitat': []}\n```",
    "```json\n{'locomocao': '...', 'sociabilidade': '...', 'atividade': ['noturna']}\n```",
    "```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "
]

In [46]:
for example in examples_string:
    format = string_to_dict(example)
    print(format)

{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}
{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': ['negro', 'branco', 'creme-acinzentada'], 'tamanho': 'Grande'}
{'habitat': []}
{'locomocao': '', 'sociabilidade': '', 'atividade': ['noturna']}
{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}

In [35]:
array_mor = df["morfologia_llm"]
array_mor = array_mor.dropna()
array_mor

0      ```json\n{'bico': 'Generalista', 'asa': 'Elípt...
1      ```json\n{'bico': 'Generalista', 'asa': '', 'p...
2      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
3      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
4      ```json\n{'bico': '', 'asa': '', 'pata': '', '...
                             ...
178    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
179    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
180    ```json\n{\n 'bico': 'Granívoro',\n 'asa': '',...
181    ```json\n{'bico': 'Insetívoro', 'asa': '', 'pa...
182    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
Name: morfologia_llm, Length: 183, dtype: object

In [43]:
array_mor[array_mor.str.contains('ariatric')]
array_mor[41]

"```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "

In [48]:
array_mor.map(string_to_dict)

0      {'bico': 'Generalista', 'asa': 'Elíptica', 'pa...
1      {'bico': 'Generalista', 'asa': '', 'pata': '',...
2      {'bico': 'Sondador', 'asa': '', 'pata': '', 'c...
3      {'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...
4      {'bico': '', 'asa': '', 'pata': '', 'cores': [...
                             ...
178    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
179    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
180    {'bico': 'Granívoro', 'asa': '', 'pata': '', '...
181    {'bico': 'Insetívoro', 'asa': '', 'pata': '', ...
182    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
Name: morfologia_llm, Length: 183, dtype: object

In [51]:
df["monforlogia_llm_json"] = df["morfologia_llm"].map(string_to_dict)
df["food_llm_json"] = df["food_llm"].map(string_to_dict)
df["habitat_llm_json"] = df["habitat_llm"].map(string_to_dict)
df["behavior_llm_json"] = df["behavior_llm"].map(string_to_dict)
df

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,...,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0,monforlogia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g..."
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,...,"Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid..."
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid..."
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,...,Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's..."
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,...,"Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,NaN,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,...,"No Brasil, ocorre nos estados do Maranhão, Par...",NaN,NaN,NaN,NaN,3682.0,{},{},{},{}
736,NaN,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,...,Ocorre especialmente nas regiões Nordeste e Su...,NaN,NaN,NaN,NaN,3684.0,{},{},{},{}
737,NaN,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,...,Ocorre nas regiões tropicais e subtropicais ao...,NaN,NaN,NaN,NaN,3695.0,{},{},{},{}
738,NaN,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,...,Ocorre em todo o Brasil e também na América Ce...,NaN,NaN,NaN,NaN,3697.0,{},{},{},{}
739,NaN,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,...,A espécie é dividida em dois grupos:,NaN,NaN,NaN,NaN,3704.0,{},{},{},{}