In [1]:
import pandas as pd

In [ ]:
path_avonet =  "data/raw/AVONET Supplementary dataset 1.xlsx"

In [3]:
df_avonet = pd.read_excel(
    path_avonet,sheet_name="AVONET2_eBird"
)
df_avonet.head()

,Species2,Family2,Order2,Avibase.ID2,Total.individuals,Female,Male,Unknown,Complete.measures,Beak.Length_Culmen,...,Mass.Refs.Other,Inference,Traits.inferred,Reference.species,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle
0,Accipiter albogularis,Accipitridae,Accipitriformes,AVIBASE-BBB59880,5,2,0,3,4,27.7,...,NaN,NO,NaN,NaN,Forest,1,2.0,Carnivore,Vertivore,Insessorial
1,Accipiter badius,Accipitridae,Accipitriformes,AVIBASE-1A0ECB6E,10,4,6,0,8,20.6,...,NaN,NO,NaN,NaN,Shrubland,2,3.0,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,Accipitridae,Accipitriformes,AVIBASE-ADBE44E1,11,4,5,2,8,25.0,...,NaN,NO,NaN,NaN,Woodland,2,2.0,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,Accipitridae,Accipitriformes,AVIBASE-68BF920B,4,4,0,0,3,22.5,...,NaN,NO,NaN,NaN,Forest,1,2.0,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,Accipitridae,Accipitriformes,AVIBASE-8492E4B7,8,4,4,0,4,21.1,...,NaN,NO,NaN,NaN,Forest,1,3.0,Carnivore,Vertivore,Generalist

In [4]:
df_avonet = df_avonet[
    [
        "Species2",
        "Beak.Length_Culmen",
        "Beak.Width",	
        "Beak.Depth",	
        "Tarsus.Length",	
        "Wing.Length",	
        "Tail.Length",
        "Mass",
        "Habitat",	
        "Habitat.Density",	
        "Migration",
        "Trophic.Level",	
        "Trophic.Niche",
        "Primary.Lifestyle"
    ]
]
df_avonet

,Species2,Beak.Length_Culmen,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,Forest,1,2.0,Carnivore,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,Shrubland,2,3.0,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,Woodland,2,2.0,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,Forest,1,2.0,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,Forest,1,3.0,Carnivore,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,Forest,1,1.0,Herbivore,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,Forest,1,1.0,Omnivore,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,Forest,1,1.0,Carnivore,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,Forest,1,1.0,Herbivore,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,Forest,1,1.0,Omnivore,Frugivore,Insessorial

In [5]:
df_avonet_new = df_avonet.rename(
    columns={
        "Species2": "taxonomia",
        "Beak.Length_Culmen": "comprimento_bico_mm",
        "Beak.Width": "largura_bico_mm",	
        "Beak.Depth": "profundidade_bico_mm",	
        "Tarsus.Length": "comprimento_tarso_mm",	
        "Wing.Length": "comprimento_asa_mm",	
        "Tail.Length": "comprimento_causa_mm",
        "Mass": "massa_corporal_g",
        "Habitat": "bioma_habitat",	
        "Habitat.Density": "densidade_habitat",	
        "Migration": "migracao",
        "Trophic.Level": "nivel_trofico",	
        "Trophic.Niche": "nicho_trofico",
        "Primary.Lifestyle": "nicho_locomotor"
    },
)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,Forest,1,2.0,Carnivore,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,Shrubland,2,3.0,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,Woodland,2,2.0,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,Forest,1,2.0,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,Forest,1,3.0,Carnivore,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,Forest,1,1.0,Herbivore,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,Forest,1,1.0,Omnivore,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,Forest,1,1.0,Carnivore,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,Forest,1,1.0,Herbivore,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,Forest,1,1.0,Omnivore,Frugivore,Insessorial

In [6]:
density_map = {
    1: "denso",
    2: "semi-aberto",
    3: "aberto"
}

df_avonet_new["densidade_habitat"] = df_avonet_new ["densidade_habitat"].map(density_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,Forest,denso,2.0,Carnivore,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,Shrubland,semi-aberto,3.0,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,Woodland,semi-aberto,2.0,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,Forest,denso,2.0,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,Forest,denso,3.0,Carnivore,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,Forest,denso,1.0,Herbivore,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,Forest,denso,1.0,Omnivore,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,Forest,denso,1.0,Carnivore,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,Forest,denso,1.0,Herbivore,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,Forest,denso,1.0,Omnivore,Frugivore,Insessorial

In [7]:
migration_map = {
    1: "sedentaria",
    2: "parcialmente migratoria",
    3: "migratoria"
}

df_avonet_new["migracao"] = df_avonet_new ["migracao"].map(migration_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,Forest,denso,parcialmente migratoria,Carnivore,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,Shrubland,semi-aberto,migratoria,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,Woodland,semi-aberto,parcialmente migratoria,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,Forest,denso,parcialmente migratoria,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,Forest,denso,migratoria,Carnivore,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,Forest,denso,sedentaria,Herbivore,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,Forest,denso,sedentaria,Omnivore,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,Forest,denso,sedentaria,Carnivore,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,Forest,denso,sedentaria,Herbivore,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,Forest,denso,sedentaria,Omnivore,Frugivore,Insessorial

In [8]:
habitat_map = {
    "Desert": "deserto",
    "Rock": "rochoso",
    "Grassland": "campo",
    "Shrubland": "arbustivo",
    "Woodland": "bosque",
    "Forest": "floresta",
    "Human modified": "ambiente antropico",
    "Wetland": "area umida",
    "Riverine":  "ribeirinho",
    "Coastal": "costeiro",
    "Marine": "marinho"
}

df_avonet_new["bioma_habitat"] = df_avonet_new ["bioma_habitat"].map(habitat_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,floresta,denso,parcialmente migratoria,Carnivore,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,arbustivo,semi-aberto,migratoria,Carnivore,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,bosque,semi-aberto,parcialmente migratoria,Carnivore,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,floresta,denso,parcialmente migratoria,Carnivore,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,floresta,denso,migratoria,Carnivore,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,floresta,denso,sedentaria,Herbivore,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,floresta,denso,sedentaria,Omnivore,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,floresta,denso,sedentaria,Carnivore,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,floresta,denso,sedentaria,Herbivore,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,floresta,denso,sedentaria,Omnivore,Frugivore,Insessorial

In [9]:
nivel_trofico_map = {
    "Herbivore": "herbivora",
    "Carnivore": "carnivora",
    "Scavenger": "necrofaga",
    "Omnivore": "onivora"
}

df_avonet_new["nivel_trofico"] = df_avonet_new ["nivel_trofico"].map(nivel_trofico_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,floresta,denso,parcialmente migratoria,carnivora,Vertivore,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,arbustivo,semi-aberto,migratoria,carnivora,Vertivore,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,bosque,semi-aberto,parcialmente migratoria,carnivora,Vertivore,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,floresta,denso,parcialmente migratoria,carnivora,Vertivore,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,floresta,denso,migratoria,carnivora,Vertivore,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,floresta,denso,sedentaria,herbivora,Frugivore,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,floresta,denso,sedentaria,onivora,Omnivore,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,floresta,denso,sedentaria,carnivora,Invertivore,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,floresta,denso,sedentaria,herbivora,Frugivore,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,floresta,denso,sedentaria,onivora,Frugivore,Insessorial

In [10]:
nicho_trofico_map = {
    "Frugivore": "frugivora",
    "Granivore": "granivora",
    "Nectarivore": "nectarivora",
    "Herbivore": "herbivora",
    "Herbivore aquatic": "herbivora aquatica",
    "Invertivore": "invertivora",
    "Vertivore": "vertivora",
    "Aquatic Predator": "predadora aquatica",
    "Scavenger": "necrofaga",
    "Omnivore": "onivora"
}

df_avonet_new["nicho_trofico"] = df_avonet_new ["nicho_trofico"].map(nicho_trofico_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,floresta,denso,parcialmente migratoria,carnivora,vertivora,Insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,arbustivo,semi-aberto,migratoria,carnivora,vertivora,Insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,bosque,semi-aberto,parcialmente migratoria,carnivora,vertivora,Generalist
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,floresta,denso,parcialmente migratoria,carnivora,vertivora,Insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,floresta,denso,migratoria,carnivora,vertivora,Generalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,floresta,denso,sedentaria,herbivora,frugivora,Insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,floresta,denso,sedentaria,onivora,onivora,Insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,floresta,denso,sedentaria,carnivora,invertivora,Insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,floresta,denso,sedentaria,herbivora,frugivora,Insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,floresta,denso,sedentaria,onivora,frugivora,Insessorial

In [11]:
nicho_locomotor_map =  {
    "Aerial": "aerea",
    "Terrestrial": "terrestre",
    "Insessorial": "insessorial",
    "Aquatic": "aquatica",
    "Generalist": "generalista"
}

df_avonet_new["nicho_locomotor"] = df_avonet_new ["nicho_locomotor"].map(nicho_locomotor_map)
df_avonet_new

,taxonomia,comprimento_bico_mm,largura_bico_mm,profundidade_bico_mm,comprimento_tarso_mm,comprimento_asa_mm,comprimento_causa_mm,massa_corporal_g,bioma_habitat,densidade_habitat,migracao,nivel_trofico,nicho_trofico,nicho_locomotor
0,Accipiter albogularis,27.7,10.6,14.7,62.0,235.2,169.0,248.8,floresta,denso,parcialmente migratoria,carnivora,vertivora,insessorial
1,Accipiter badius,20.6,8.8,11.6,43.0,186.7,140.6,131.2,arbustivo,semi-aberto,migratoria,carnivora,vertivora,insessorial
2,Accipiter bicolor,25.0,8.6,12.7,58.1,229.6,186.3,287.5,bosque,semi-aberto,parcialmente migratoria,carnivora,vertivora,generalista
3,Accipiter brachyurus,22.5,8.9,11.9,61.2,202.2,140.8,142.0,floresta,denso,parcialmente migratoria,carnivora,vertivora,insessorial
4,Accipiter brevipes,21.1,8.7,11.1,46.4,217.6,153.5,186.5,floresta,denso,migratoria,carnivora,vertivora,generalista
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10656,Trogon ramonianus,19.4,10.4,8.6,11.7,115.5,122.7,43.4,floresta,denso,sedentaria,herbivora,frugivora,insessorial
10657,Trogon rufus,19.9,8.9,9.8,13.1,113.1,130.9,53.8,floresta,denso,sedentaria,onivora,onivora,insessorial
10658,Trogon surrucura,19.5,9.3,9.9,15.3,133.2,132.7,73.3,floresta,denso,sedentaria,carnivora,invertivora,insessorial
10659,Trogon violaceus,19.0,9.0,9.4,10.8,114.0,104.0,46.5,floresta,denso,sedentaria,herbivora,frugivora,insessorial
10660,Trogon viridis,25.2,10.1,11.7,14.2,146.1,158.4,89.7,floresta,denso,sedentaria,onivora,frugivora,insessorial

In [ ]:
df_avonet_new.to_json(
    "data/interim/avonet_bird_morphology_global.json",
    orient="records",
    force_ascii=False
)