In [2]:
import pandas as pd
import numpy as np

In [3]:
path_res = "../data/oficial/result_llm_wikiaves_udi.json"
path_par = "../data/oficial/parameterized_dataset_udi.json"
path_scr = "../data/treat/result_scraper_wikiaves_udi.json"

In [4]:
df_res = pd.read_json(path_res)
df_par = pd.read_json(path_par)
df_scr = pd.read_json(path_scr)

In [6]:
print(
    "DF_RESULT - "
    "Total: " + str(len(df_res)),
    "Nulos:" + str(df_res['morfologia_llm'].isna().sum()),
    "Duplicados: " + str(len(df_res[df_res['taxonomia'].duplicated(keep=False)]['taxonomia'].value_counts())),
)
print(
    "DF_PARA - "
    "Total: " + str(len(df_par)),
    "Nulos:" + str(df_par['cores'].isna().sum()),
    "Duplicados: " + str(len(df_par[df_par['taxonomia'].duplicated(keep=False)]['taxonomia'].value_counts())),
)
print(
    "DF_SCRAPER - "
    "Total: " + str(len(df_scr)),
    "Duplicados: " + str(len(df_scr[df_scr['taxonomia'].duplicated(keep=False)]['taxonomia'].value_counts())),
)

DF_RESULT - Total: 740 Nulos:0 Duplicados: 370
DF_PARA - Total: 287 Nulos:0 Duplicados: 0
DF_SCRAPER - Total: 740 Duplicados: 370

In [7]:
df_res = df_res.drop_duplicates(subset='taxonomia', keep='first')
df_par = df_par.drop_duplicates(subset='taxonomia', keep='first')
df_scr = df_scr.drop_duplicates(subset='taxonomia', keep='first')

In [8]:
len(df_scr)

370

In [ ]:
#df_scr.to_json("../data/treat/dedup_result_scraper_wikiaves_udi.json", orient="records")

## Merge dedup + resume + parameterizes

In [9]:
df_par.to_json("../data/treat/parameterized_dataset_udi.json", orient="records")

In [7]:
df_dedup_result = pd.read_json("../data/treat/dedup_result_scraper_wikiaves_udi.json")
df_par = pd.read_json("../data/treat/new_parameterized_dataset_udi.json")

In [8]:
df_dedup_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0                    158 non-null    float64
 1   taxonomia        370 non-null    object
 2   ordem            370 non-null    object
 3   familia          370 non-null    object
 4   subfamilia       328 non-null    object
 5   genero           370 non-null    object
 6   especie          370 non-null    object
 7   nome_pt          370 non-null    object
 8   nome_eng         370 non-null    object
 9   url_wikiaves     370 non-null    object
 10  caracteristicas  369 non-null    object
 11  alimentacao      368 non-null    object
 12  reproducao       369 non-null    object
 13  habitos          368 non-null    object
 14  dist_geo         367 non-null    object
 15  Unnamed: 0       212 non-null    float64
 16  url_image        369 non-null    object
 17  resumo_llm       325 non-null    object
dtypes: float64(2), object(16)
memory usage: 52.2+ KB

In [9]:
df_dedup_result = df_dedup_result.drop(columns=["Unnamed: 0",""])
df_dedup_result

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,url_image,resumo_llm
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,https://s3.amazonaws.com/media.wikiaves.com.br...,"A ema (Rhea americana) é uma ave ratita, a mai..."
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...",https://s3.amazonaws.com/media.wikiaves.com.br...,"A espécie Crypturellus undulatus, conhecida co..."
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,https://s3.amazonaws.com/media.wikiaves.com.br...,"Crypturellus parvirostris, conhecido como inha..."
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,https://s3.amazonaws.com/media.wikiaves.com.br...,"Rhynchotus rufescens, uma ave terrícola da fam..."
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...",https://s3.amazonaws.com/media.wikiaves.com.br...,A espécie *Nothura maculosa* é uma ave de pequ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,"Granívoro. Alimenta-se também de frutos, algum...",Ocorrem 2 ou 3 posturas por temporada. Põe 2 o...,"Pode ser encontrado em cerrados, caatingas, ca...","Ocorre nos estados do Maranhão, Pará, Bahia, P...",https://s3.amazonaws.com/media.wikiaves.com.br...,NaN
366,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",Predominantemente granívoro com adaptação para...,Durante a reprodução vive estritamente aos cas...,Habita mata baixa rala e bem ensolarada (caati...,Ocorre especialmente nas regiões Nordeste e Su...,https://s3.amazonaws.com/media.wikiaves.com.br...,NaN
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,"Frutos, costuma consumir muito o fruto da aroe...","O ninho, construído pelo casal, é compacto, fe...","Habita matas abertas, capões, matas ciliares, ...",Ocorre nas regiões tropicais e subtropicais ao...,https://s3.amazonaws.com/media.wikiaves.com.br...,NaN
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,"Caça insetos no meio das folhas, às vezes fica...",Possui um chamado de notas agudas e assobiadas...,"Muito ativo, vive em casais e pequenos grupos,...",Ocorre em todo o Brasil e também na América Ce...,https://s3.amazonaws.com/media.wikiaves.com.br...,NaN
369,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,Essa saíra se alimenta de frutos e insetos com...,"O ninho, em forma de taça aberta, é feito com ...","Habita capoeiras, matas abertas e ciliares, ár...",A espécie é dividida em dois grupos:,https://s3.amazonaws.com/media.wikiaves.com.br...,NaN

In [10]:
df_par.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   taxonomia               370 non-null    object
 1   ordem                   370 non-null    object
 2   familia                 370 non-null    object
 3   subfamilia              250 non-null    object
 4   genero                  370 non-null    object
 5   especie                 370 non-null    object
 6   nome_pt                 370 non-null    object
 7   nome_eng                370 non-null    object
 8   url_wikiaves            370 non-null    object
 9   caracteristicas         369 non-null    object
 10  alimentacao             368 non-null    object
 11  reproducao              367 non-null    object
 12  habitos                 368 non-null    object
 13  dist_geo                359 non-null    object
 14  url_image               369 non-null    object
 15  resumo_llm              184 non-null    object
 16  formato_asa             73 non-null     object
 17  tipo_pata               53 non-null     object
 18  cores                   287 non-null    object
 19  tamanho                 269 non-null    object
 20  caracteristica_trofica  280 non-null    object
 21  dieta_principal         286 non-null    object
 22  habitat                 287 non-null    object
 23  locomocao               269 non-null    object
 24  sociabilidade           211 non-null    object
 25  atividade               287 non-null    object
 26  tipo_bico               270 non-null    object
dtypes: object(27)
memory usage: 78.2+ KB

In [11]:
df_left_join = pd.merge(df_dedup_result, df_par, on="taxonomia", how="left")
df_left_join

,taxonomia,ordem_x,familia_x,subfamilia_x,genero_x,especie_x,nome_pt_x,nome_eng_x,url_wikiaves_x,caracteristicas_x,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Anizodáctilo,"[cinza, preto, amarelado]",grande,onivoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,None,[],media,onivoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",None,None,[diurna],generalista
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,None,"[marrom avermelhado, acinzentado]",None,onivoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",None,None,"[diurna, crepuscular]",sondador
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",media,onivoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,None,"[marrons, amarelo, branco]",pequena,onivoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,None,None,None,None,None,None,None,None,None,None
366,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,None,"[vermelho, cinza, preto, branco, pardo]",media,granivoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,None,[diurna],generalista
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,Anizodáctilo,"[cinza, azul turquesa, esverdeado, branco]",pequena,onivoro,"[frutas, sementes, insectos]","[mata ciliar, zona de cultivo, mato aberto, ár...",voadora,gregária,[diurna],generalista
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,None,"[esverdeada, amarelada]",media,onivoro,"[insetos, néctar, frutos]","[área urbana, floresta aberta, campo natural]",voadora,gregária,[diurna],generalista
369,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,None,None,None,None,None,None,None,None,None,None

In [12]:
df_left_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   taxonomia               370 non-null    object
 1   ordem_x                 370 non-null    object
 2   familia_x               370 non-null    object
 3   subfamilia_x            328 non-null    object
 4   genero_x                370 non-null    object
 5   especie_x               370 non-null    object
 6   nome_pt_x               370 non-null    object
 7   nome_eng_x              370 non-null    object
 8   url_wikiaves_x          370 non-null    object
 9   caracteristicas_x       369 non-null    object
 10  alimentacao_x           368 non-null    object
 11  reproducao_x            369 non-null    object
 12  habitos_x               368 non-null    object
 13  dist_geo_x              367 non-null    object
 14  url_image_x             369 non-null    object
 15  resumo_llm_x            325 non-null    object
 16  ordem_y                 370 non-null    object
 17  familia_y               370 non-null    object
 18  subfamilia_y            250 non-null    object
 19  genero_y                370 non-null    object
 20  especie_y               370 non-null    object
 21  nome_pt_y               370 non-null    object
 22  nome_eng_y              370 non-null    object
 23  url_wikiaves_y          370 non-null    object
 24  caracteristicas_y       369 non-null    object
 25  alimentacao_y           368 non-null    object
 26  reproducao_y            367 non-null    object
 27  habitos_y               368 non-null    object
 28  dist_geo_y              359 non-null    object
 29  url_image_y             369 non-null    object
 30  resumo_llm_y            184 non-null    object
 31  formato_asa             73 non-null     object
 32  tipo_pata               53 non-null     object
 33  cores                   287 non-null    object
 34  tamanho                 269 non-null    object
 35  caracteristica_trofica  280 non-null    object
 36  dieta_principal         286 non-null    object
 37  habitat                 287 non-null    object
 38  locomocao               269 non-null    object
 39  sociabilidade           211 non-null    object
 40  atividade               287 non-null    object
 41  tipo_bico               270 non-null    object
dtypes: object(42)
memory usage: 121.5+ KB

In [13]:
df_left_join.columns

Index(['taxonomia', 'ordem_x', 'familia_x', 'subfamilia_x', 'genero_x',
       'especie_x', 'nome_pt_x', 'nome_eng_x', 'url_wikiaves_x',
       'caracteristicas_x', 'alimentacao_x', 'reproducao_x', 'habitos_x',
       'dist_geo_x', 'url_image_x', 'resumo_llm_x', 'ordem_y', 'familia_y',
       'subfamilia_y', 'genero_y', 'especie_y', 'nome_pt_y', 'nome_eng_y',
       'url_wikiaves_y', 'caracteristicas_y', 'alimentacao_y', 'reproducao_y',
       'habitos_y', 'dist_geo_y', 'url_image_y', 'resumo_llm_y', 'formato_asa',
       'tipo_pata', 'cores', 'tamanho', 'caracteristica_trofica',
       'dieta_principal', 'habitat', 'locomocao', 'sociabilidade', 'atividade',
       'tipo_bico'],
      dtype='object')

In [17]:
df_left_join = df_left_join[['taxonomia', 'ordem_x', 'familia_x', 'subfamilia_x', 'genero_x',
       'especie_x', 'nome_pt_x', 'nome_eng_x', 'url_wikiaves_x',
       'caracteristicas_x', 'alimentacao_x', 'reproducao_x', 'habitos_x',
       'dist_geo_x', 'resumo_llm_x', "url_image_x",'formato_asa', 'tipo_pata', 'cores',
       'tamanho', 'caracteristica_trofica', 'dieta_principal', 'habitat',
       'locomocao', 'sociabilidade', 'atividade', 'tipo_bico']]

In [18]:
df_left_join = df_left_join.rename(
    columns={
        'ordem_x': 'ordem',
        'familia_x': 'familia',
        'subfamilia_x': 'subfamilia',
        'genero_x': 'genero',
        'especie_x': 'especie',
        'nome_pt_x': 'nome_pt',
        'nome_eng_x': 'nome_eng',
        'url_wikiaves_x': 'url_wikiaves',
        'caracteristicas_x': 'caracteristicas',
        'alimentacao_x': 'alimentacao',
        'reproducao_x': 'reproducao',
        'habitos_x': 'habitos',
        'dist_geo_x': 'dist_geo',
        'resumo_llm_x' : 'resumo_llm',
        "url_image_x": 'url_image',
    }
)
df_left_join

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Anizodáctilo,"[cinza, preto, amarelado]",grande,onivoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,None,[],media,onivoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",None,None,[diurna],generalista
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,None,"[marrom avermelhado, acinzentado]",None,onivoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",None,None,"[diurna, crepuscular]",sondador
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",media,onivoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,None,"[marrons, amarelo, branco]",pequena,onivoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,None,None,None,None,None,None,None,None,None,None
366,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,None,"[vermelho, cinza, preto, branco, pardo]",media,granivoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,None,[diurna],generalista
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,Anizodáctilo,"[cinza, azul turquesa, esverdeado, branco]",pequena,onivoro,"[frutas, sementes, insectos]","[mata ciliar, zona de cultivo, mato aberto, ár...",voadora,gregária,[diurna],generalista
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,None,"[esverdeada, amarelada]",media,onivoro,"[insetos, néctar, frutos]","[área urbana, floresta aberta, campo natural]",voadora,gregária,[diurna],generalista
369,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,None,None,None,None,None,None,None,None,None,None

In [19]:
df_left_join = df_left_join.replace(["", None], np.nan)
df_left_join

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
0,Rhea americana,Rheiformes,Rheidae,NaN,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Anizodáctilo,"[cinza, preto, amarelado]",grande,onivoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista
1,Crypturellus undulatus,Tinamiformes,Tinamidae,NaN,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,NaN,[],media,onivoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",NaN,NaN,[diurna],generalista
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,NaN,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,NaN,"[marrom avermelhado, acinzentado]",NaN,onivoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",NaN,NaN,"[diurna, crepuscular]",sondador
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,NaN,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",media,onivoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador
4,Nothura maculosa,Tinamiformes,Tinamidae,NaN,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,NaN,"[marrons, amarelo, branco]",pequena,onivoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,NaN,"[vermelho, cinza, preto, branco, pardo]",media,granivoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,NaN,[diurna],generalista
367,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,Anizodáctilo,"[cinza, azul turquesa, esverdeado, branco]",pequena,onivoro,"[frutas, sementes, insectos]","[mata ciliar, zona de cultivo, mato aberto, ár...",voadora,gregária,[diurna],generalista
368,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,NaN,"[esverdeada, amarelada]",media,onivoro,"[insetos, néctar, frutos]","[área urbana, floresta aberta, campo natural]",voadora,gregária,[diurna],generalista
369,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df_left_join.to_json("../data/treat/new_parameterized_dataset_udi.json", orient="records")

In [20]:
df_left_join["tamanho"].unique()

array(['grande', 'media', nan, 'pequena'], dtype=object)

In [41]:
df_left_join.loc[df_left_join["tamanho"]=='Grande','tamanho'] = 'grande'
df_left_join.loc[df_left_join["tamanho"]=='Médio','tamanho'] = 'media'
df_left_join.loc[df_left_join["tamanho"]=='médio','tamanho'] = 'media'
df_left_join.loc[df_left_join["tamanho"]=='Pequeno','tamanho'] = 'pequena'
df_left_join.loc[df_left_join["tamanho"]=='pequeno','tamanho'] = 'pequena'

In [22]:
df_left_join.loc[df_left_join["familia"]=="Strigidae", "tipo_bico"] = "raptorial"
df_left_join.loc[df_left_join["familia"]=="Strigidae"]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
124,Megascops choliba,Strigiformes,Strigidae,NaN,Megascops,choliba,corujinha-do-mato,Tropical Screech-Owl,https://www.wikiaves.com.br/wiki/corujinha-do-...,"Menor do que a coruja-buraqueira, medindo entr...",...,NaN,"[cinza, preto, amarelo, cinza amarronzado, mar...",pequena,insetivoro,"[artrópodes, gafanhotos, aranhas, escorpiões, ...","[área urbana, capoeira, beira de mata]",voadora,solitária,[noturna],raptorial
125,Bubo virginianus,Strigiformes,Strigidae,NaN,Bubo,virginianus,jacurutu,Great Horned Owl,https://www.wikiaves.com.br/wiki/jacurutu,Dimensões(Relativas):,...,Anizodáctilo,[],NaN,carnivoro,[tartaruguinhas],"[mata ciliar, campo natural, cerrado]",trepadora,territorial,[noturna],raptorial
126,Strix virgata,Strigiformes,Strigidae,NaN,Strix,virgata,coruja-do-mato,Mottled Owl,https://www.wikiaves.com.br/wiki/coruja-do-mato,Tem entre 33 e 41 centímetros (macho) e 32 e 3...,...,NaN,"[marrom-escuro, branco, bege claro]",media,onivoro,"[insetos, mamíferos, répteis, anfíbios, aves]","[mata ciliar, floresta aberta, plantação]",trepadora,territorial,[noturna],raptorial
127,Glaucidium brasilianum,Strigiformes,Strigidae,NaN,Glaucidium,brasilianum,caburé,Ferruginous Pygmy-Owl,https://www.wikiaves.com.br/wiki/cabure,"Medindo cerca de 16,5 centímetros, a corujinha...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,raptorial
128,Athene cunicularia,Strigiformes,Strigidae,NaN,Athene,cunicularia,coruja-buraqueira,Burrowing Owl,https://www.wikiaves.com.br/wiki/coruja-buraqu...,"Ave de pequeno porte, seu tamanho médio é de 2...",...,Anizodáctilo,"[cor de terra, ferrugem, branco, amarelo, pard...",pequena,insetivoro,"[roedores, besouros, grilos, gafanhotos]","[campo natural, área urbana]",voadora,gregária,"[diurna, noturna, crepuscular]",raptorial
129,Asio clamator,Strigiformes,Strigidae,NaN,Asio,clamator,coruja-orelhuda,Striped Owl,https://www.wikiaves.com.br/wiki/coruja-orelhuda,"Coruja de tamanho médio, medindo de 34 a 42 cm...",...,Anizodáctilo,"[bege, marrom, canela, preto, branco, esbranqu...",media,carnivoro,"[ratos, morcegos, anfíbios, répteis, insetos, ...","[mata, cerrado, área alagada, campo de cultivo...",voadora,NaN,"[noturna, crepuscular]",raptorial
130,Asio stygius,Strigiformes,Strigidae,NaN,Asio,stygius,mocho-diabo,Stygian Owl,https://www.wikiaves.com.br/wiki/mocho-diabo,"Coruja de tamanho médio-grande, variando de 40...",...,NaN,"[cinza amarronzada, acinzentada, marrom escuro...",media,carnivoro,"[pequenos mamíferos, aves, insetos]",[floresta aberta],TREPADORA,NaN,[noturna],raptorial
131,Asio flammeus,Strigiformes,Strigidae,NaN,Asio,flammeus,mocho-dos-banhados,Short-eared Owl,https://www.wikiaves.com.br/wiki/mocho-dos-ban...,"Esta é uma coruja com cerca de 33 a 41,5 cm (m...",...,NaN,"[escuro, claro]",media,carnivoro,"[roedores, morcegos, aves, insetos]","[campo natural, área urbana, área alagada]",voadora,NaN,[diurna],raptorial

In [24]:
df_left_join.loc[df_left_join["familia"]=="Tytonidae", "tipo_bico"] = "raptorial"
df_left_join.loc[df_left_join["familia"]=="Tytonidae"]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
123,Tyto furcata,Strigiformes,Tytonidae,NaN,Tyto,furcata,suindara,American Barn Owl,https://www.wikiaves.com.br/wiki/suindara,Possui em média 33 a 36 centímetros (macho) e ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,raptorial

In [26]:
df_left_join.loc[df_left_join["familia"]=="Threskiornithidae", "tipo_bico"] = "sondador"
df_left_join.loc[df_left_join["familia"]=="Threskiornithidae"]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
92,Mesembrinibis cayennensis,Pelecaniformes,Threskiornithidae,NaN,Mesembrinibis,cayennensis,coró-coró,Green Ibis,https://www.wikiaves.com.br/wiki/coro-coro,O adulto mede entre 48 e 56 centímetros de com...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sondador
93,Phimosus infuscatus,Pelecaniformes,Threskiornithidae,NaN,Phimosus,infuscatus,tapicuru,Bare-faced Ibis,https://www.wikiaves.com.br/wiki/tapicuru,Mede entre 46 e 54 centímetros de comprimento ...,...,NaN,"[preto, amarelo alaranjado, amarelo]",media,onivoro,"[crustáceos, moluscos, sementes, folhas]","[brejo, margens de rios, banhados, campos rece...",voadora,gregária,[diurna],sondador
94,Theristicus caudatus,Pelecaniformes,Threskiornithidae,NaN,Theristicus,caudatus,curicaca,Buff-necked Ibis,https://www.wikiaves.com.br/wiki/curicaca,O macho costuma ser um pouco maior que a fêmea...,...,NaN,"[cinzento-claro, esverdeado, preto, branco]",media,onivoro,"[artrópodes, lagartos, ratos, caramujos, anfíb...","[campo natural, área alagada]",voadora,gregária,"[diurna, crepuscular]",sondador
95,Platalea ajaja,Pelecaniformes,Threskiornithidae,NaN,Platalea,ajaja,colhereiro,Roseate Spoonbill,https://www.wikiaves.com.br/wiki/colhereiro,"O colhereiro mede entre 68,5 e 86,5 centímetro...",...,Anizodáctilo,"[rosa, avermelhado, branco, cinza]",media,insetivoro,"[insetos, peixes, camarões, moluscos, crustáce...","[área alagada, mangue]",voadora,gregária,[diurna],sondador

In [30]:
df_left_join.loc[df_left_join["familia"]=="Ardeidae", "tipo_bico"] = "pescador"
df_left_join.loc[df_left_join["familia"]=="Ardeidae"]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
83,Tigrisoma lineatum,Pelecaniformes,Ardeidae,NaN,Tigrisoma,lineatum,socó-boi,Rufescent Tiger-Heron,https://www.wikiaves.com.br/wiki/soco-boi,Mede entre 66 e 76 centímetros de comprimento ...,...,NaN,"[castanho, branco, pardo-acinzentado, acinzent...",media,onivoro,"[crustáceos, répteis, anfíbios, peixes, insetos]","[brejo, pantanal, área alagada, floresta aberta]",voadora,solitária,"[diurna, crepuscular]",pescador
84,Nycticorax nycticorax,Pelecaniformes,Ardeidae,NaN,Nycticorax,nycticorax,socó-dorminhoco,Black-crowned Night-Heron,https://www.wikiaves.com.br/wiki/soco-dorminhoco,"Apresenta o alto da cabeça e o dorso negros, a...",...,NaN,"[preto, cinza, marrom-claro, tons mais escuros...",media,onivoro,"[peixes, anfíbios, crustáceos, insetos, réptei...","[área alagada, rio, lago, lagoa]",trepadora,gregária,"[noturna, crepuscular]",pescador
85,Butorides striata,Pelecaniformes,Ardeidae,NaN,Butorides,striata,socozinho,Striated Heron,https://www.wikiaves.com.br/wiki/socozinho,"Tem cerca de 36 centímetros. É inconfundível, ...",...,NaN,"[amarelo, azulado]",media,onivoro,"[peixes, insetos, caranguejos, moluscos, anfíb...","[área alagada, manguezais]",trepadora,NaN,"[diurna, crepuscular]",pescador
86,Bubulcus ibis,Pelecaniformes,Ardeidae,NaN,Bubulcus,ibis,garça-vaqueira,Cattle Egret,https://www.wikiaves.com.br/wiki/garca-vaqueira,Apresenta um comprimento de 48 a 53 centímetro...,...,NaN,"[branco, laranja pálido, amarelo, avermelhado,...",media,onivoro,"[insetos, moluscos, crustáceos, anfíbios, pequ...","[campo natural, plantação, pampa, área alagada...",voadora,gregária,[diurna],pescador
87,Ardea cocoi,Pelecaniformes,Ardeidae,NaN,Ardea,cocoi,garça-moura,Cocoi Heron,https://www.wikiaves.com.br/wiki/garca-moura,"A maior das garças do Brasil, com envergadura ...",...,NaN,[],grande,carnivoro,"[peixes, sapos, rãs, pererecas, caranguejos, m...","[rio, riacho, lagos, estuários, manguezais, pâ...",voadora,territorial,[diurna],pescador
88,Ardea alba,Pelecaniformes,Ardeidae,NaN,Ardea,alba,garça-branca-grande,Great Egret,https://www.wikiaves.com.br/wiki/garca-branca-...,Mede entre 65 e 104 centímetros de comprimento...,...,Anizodáctilo,"[branco, amarelo, amarelo-alaranjado, preto, e...",grande,onivoro,"[peixes, roedores, anfíbios, répteis, insetos,...","[área alagada, rios, lagos, banhados, praias, ...",voadora,gregária,[diurna],pescador
89,Syrigma sibilatrix,Pelecaniformes,Ardeidae,NaN,Syrigma,sibilatrix,maria-faceira,Whistling Heron,https://www.wikiaves.com.br/wiki/maria-faceira,Mede entre 53 e 64 centímetros de comprimento ...,...,NaN,"[azul-claro, cinza-escuro, preto, amarelo, bra...",media,onivoro,"[insetos, anfíbios, roedores, peixes]","[campo natural, plantação, cerrado, savana, ár...",trepadora,territorial,"[diurna, crepuscular]",pescador
90,Pilherodius pileatus,Pelecaniformes,Ardeidae,NaN,Pilherodius,pileatus,garça-real,Capped Heron,https://www.wikiaves.com.br/wiki/garca-real,"Mede 51 a 59 cm, 444-632 g. Sexos semelhantes....",...,Zigodáctilo,"[preto, branco, cinza, creme, amarelado, azul,...",media,carnivoro,"[peixes, sapos, rãs, insetos, crustáceos]","[rios, lagos, margens florestadas, áreas panta...",voadora,territorial,[diurna],pescador
91,Egretta thula,Pelecaniformes,Ardeidae,NaN,Egretta,thula,garça-branca-pequena,Snowy Egret,https://www.wikiaves.com.br/wiki/garca-branca-...,"Mede 54 a 66 cm, com envergadura de 100 cm e p...",...,Anizodáctilo,"[branco, preto, amarelo, avermelhado, alaranjado]",media,onivoro,"[peixes, insetos, moluscos, vermes, caranguejo...","[área alagada, mangue, estuário, costa, planta...",corredora,gregária,[diurna],pescador

In [31]:
df_left_join.columns

Index(['taxonomia', 'ordem', 'familia', 'subfamilia', 'genero', 'especie',
       'nome_pt', 'nome_eng', 'url_wikiaves', 'caracteristicas', 'alimentacao',
       'reproducao', 'habitos', 'dist_geo', 'resumo_llm', 'url_image',
       'formato_asa', 'tipo_pata', 'cores', 'tamanho',
       'caracteristica_trofica', 'dieta_principal', 'habitat', 'locomocao',
       'sociabilidade', 'atividade', 'tipo_bico'],
      dtype='object')

In [32]:
df_left_join.to_json("../data/treat/dedup2_result_scraper_wikiaves_udi.json", orient="records")