In [3]:
import pandas as pd
import numpy as np

import json
import ast
import re

## Raw Dataframe

In [40]:
path_json = "../data/oficial/result_llm_wikiaves_udi.json"
df = pd.read_json(path_json)
df.head()

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN

In [41]:
def string_to_dict(string_input):
    try:
        match = re.search(r'```json\s*(.*?)\s*```', string_input, re.DOTALL)

        content = match.group(1)

        string_clean = re.sub(r'^```json\n|\n```$','',content.strip())
        string_clean = string_clean.replace('\\','')
        string_clean = string_clean.replace('...','')

        try:
            string_json = json.loads(string_clean)
        except json.JSONDecodeError:
            string_json = ast.literal_eval(string_clean)
        
        return string_json
    except:
        return {}

In [42]:
examples_string = [
    "```json\n{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}\n```",
    "```json\n{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': [\"negro\", \"branco\", \"creme-acinzentada\"], 'tamanho': 'Grande'} \n```",
    "```json\n{'habitat': []}\n```",
    "```json\n{'locomocao': '...', 'sociabilidade': '...', 'atividade': ['noturna']}\n```",
    "```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "
]

In [43]:
for example in examples_string:
    format = string_to_dict(example)
    print(format)

{'locomocao': 'voadora', 'sociabilidade': 'solitária', 'atividade': ['diurna']}
{'bico': 'Pescador', 'asa': 'Pernalta', 'pata': 'Palmada', 'cores': ['negro', 'branco', 'creme-acinzentada'], 'tamanho': 'Grande'}
{'habitat': []}
{'locomocao': '', 'sociabilidade': '', 'atividade': ['noturna']}
{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}

In [44]:
array_mor = df["morfologia_llm"]
array_mor = array_mor.dropna()
array_mor

0      ```json\n{'bico': 'Generalista', 'asa': 'Elípt...
1      ```json\n{'bico': 'Generalista', 'asa': '', 'p...
2      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
3      ```json\n{'bico': 'Sondador', 'asa': '', 'pata...
4      ```json\n{'bico': '', 'asa': '', 'pata': '', '...
                             ...
735    ```json\n{'bico': 'Generalista', 'asa': '', 'p...
736    ```json\n{'bico': 'Granívoro', 'asa': '', 'pat...
737    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
738    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
739    ```json\n{'bico': '', 'asa': '', 'pata': '', '...
Name: morfologia_llm, Length: 740, dtype: object

In [45]:
array_mor[array_mor.str.contains('ariatric')]
array_mor[41]

"```json\n{'bico': 'Insetívoro', 'asa': 'Elíptica', 'pata': '', 'cores': [], 'tamanho': 'Pequeno'}\n```ariatric  "

In [46]:
array_mor.map(string_to_dict)

0      {'bico': 'Generalista', 'asa': 'Elíptica', 'pa...
1      {'bico': 'Generalista', 'asa': '', 'pata': '',...
2      {'bico': 'Sondador', 'asa': '', 'pata': '', 'c...
3      {'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...
4      {'bico': '', 'asa': '', 'pata': '', 'cores': [...
                             ...
735    {'bico': 'Generalista', 'asa': '', 'pata': '',...
736    {'bico': 'Granívoro', 'asa': '', 'pata': '', '...
737    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
738    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
739    {'bico': '', 'asa': '', 'pata': '', 'cores': [...
Name: morfologia_llm, Length: 740, dtype: object

## Treat JSON LLM

In [11]:
df["morfologia_llm_json"] = df["morfologia_llm"].map(string_to_dict)
df["food_llm_json"] = df["food_llm"].map(string_to_dict)
df["habitat_llm_json"] = df["habitat_llm"].map(string_to_dict)
df["behavior_llm_json"] = df["behavior_llm"].map(string_to_dict)
df

,,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,...,dist_geo,morfologia_llm,food_llm,habitat_llm,behavior_llm,Unnamed: 0,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json
0,0.0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,...,R (Comitê Brasileiro de Registros Ornitológico...,"```json\n{'bico': 'Generalista', 'asa': 'Elípt...","```json\n{'tipo': 'onívoro', 'itens': ['folhas...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g..."
1,8.0,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,...,"Região norte, oeste da região Nordeste, Centro...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['mata ciliar', 'cerrado'...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid..."
2,18.0,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,...,Ocorre em quase todo território brasileiro des...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'campo natura...","```json\n{'locomocao': '', 'sociabilidade': ''...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid..."
3,20.0,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,...,Todo o Brasil até o sul do rio Amazonas e tamb...,"```json\n{'bico': 'Sondador', 'asa': '', 'pata...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'cerrad...","```json\n{'locomocao': 'corredora', 'sociabili...",NaN,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's..."
4,23.0,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,...,"Ocorre nas regiões norte (no Tocantins), Norde...","```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['grãos'...","```json\n{'habitat': ['campo natural', 'planta...","```json\n{'locomocao': 'voadora', 'sociabilida...",NaN,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,NaN,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,...,"No Brasil, ocorre nos estados do Maranhão, Par...","```json\n{'bico': 'Generalista', 'asa': '', 'p...","```json\n{'tipo': 'onívoro', 'itens': ['sement...","```json\n{'habitat': ['cerrado', 'caatinga', '...","```json\n{'locomocao': '...', 'sociabilidade':...",3682.0,"{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['sementes', 'fru...","{'habitat': ['cerrado', 'caatinga', 'campo nat...","{'locomocao': '', 'sociabilidade': 'territoria..."
736,NaN,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,...,Ocorre especialmente nas regiões Nordeste e Su...,"```json\n{'bico': 'Granívoro', 'asa': '', 'pat...","```json\n{'tipo': 'granívoro', 'itens': ['seme...","```json\n{'habitat': ['caatinga', 'cerrado']}\...","```json\n{'locomocao': 'voadora', 'sociabilida...",3684.0,"{'bico': 'Granívoro', 'asa': '', 'pata': '', '...","{'tipo': 'granívoro', 'itens': ['sementes', 'f...","{'habitat': ['caatinga', 'cerrado']}","{'locomocao': 'voadora', 'sociabilidade': '', ..."
737,NaN,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,...,Ocorre nas regiões tropicais e subtropicais ao...,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['capoe', 'mata ciliar', ...","```json\n{'locomocao': 'voadora', 'sociabilida...",3695.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoe', 'mata ciliar', 'zona de ...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
738,NaN,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,...,Ocorre em todo o Brasil e também na América Ce...,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['inseto...","```json\n{'habitat': ['campo natural', 'flores...","```json\n{'locomocao': 'voadora', 'sociabilida...",3697.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['insetos', 'frut...","{'habitat': ['campo natural', 'floresta aberta...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
739,NaN,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,...,A espécie é dividida em dois grupos:,"```json\n{'bico': '', 'asa': '', 'pata': '', '...","```json\n{'tipo': 'onívoro', 'itens': ['frutas...","```json\n{'habitat': ['capoeira', 'área ciliar...","```json\n{'locomocao': '', 'sociabilidade': 'g...",3704.0,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoeira', 'área ciliar', 'área ...","{'locomocao': '', 'sociabilidade': 'gregária',..."

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0                        158 non-null    float64
 1   taxonomia            740 non-null    object
 2   ordem                740 non-null    object
 3   familia              740 non-null    object
 4   subfamilia           578 non-null    object
 5   genero               740 non-null    object
 6   especie              740 non-null    object
 7   nome_pt              740 non-null    object
 8   nome_eng             740 non-null    object
 9   url_wikiaves         740 non-null    object
 10  caracteristicas      739 non-null    object
 11  alimentacao          737 non-null    object
 12  reproducao           739 non-null    object
 13  habitos              737 non-null    object
 14  dist_geo             735 non-null    object
 15  morfologia_llm       740 non-null    object
 16  food_llm             740 non-null    object
 17  habitat_llm          740 non-null    object
 18  behavior_llm         740 non-null    object
 19  Unnamed: 0           582 non-null    float64
 20  morfologia_llm_json  740 non-null    object
 21  food_llm_json        740 non-null    object
 22  habitat_llm_json     740 non-null    object
 23  behavior_llm_json    740 non-null    object
dtypes: float64(2), object(22)
memory usage: 138.9+ KB

In [13]:
new_df = df[
    [
        'taxonomia', 'ordem', 'familia','subfamilia','genero',
        'especie','nome_pt','nome_eng','url_wikiaves','caracteristicas',
        'alimentacao','reproducao','habitos','dist_geo',
        'morfologia_llm_json','food_llm_json','habitat_llm_json','behavior_llm_json'
    ]
]
new_df

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,alimentacao,reproducao,habitos,dist_geo,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,"São onívoros, comendo folhas, inclusive as esp...","A ema só vocaliza na época do acasalamento, qu...",A ema é uma ave corredora que ocorre em paisag...,R (Comitê Brasileiro de Registros Ornitológico...,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g..."
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,"Alimenta-se de pequenos frutos caídos no chão,...","O pio serve para demarcar sua área de vida e, ...","Habita a mata de várzea e galeria, capoeira, m...","Região norte, oeste da região Nordeste, Centro...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid..."
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",Alimenta-se de pequenas sementes diversas (nat...,Ao macho compete a incubação dos ovos e o trat...,O inhambu-chororó vocaliza habitualmente ao am...,Ocorre em quase todo território brasileiro des...,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid..."
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,Alimenta-se buscando o alimento ciscando o sol...,"O ninho da perdiz é um buraquinho na terra, fo...","Vive nos campos sujos, cerrados, buritizais e ...",Todo o Brasil até o sul do rio Amazonas e tamb...,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's..."
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,"Gosta de comer grãos, artrópodes, moluscos e t...","Põe de 7 a 8 ovos, que são cor chocolate-escur...","Vive em campos rupestres de altitude, campos r...","Ocorre nas regiões norte (no Tocantins), Norde...","{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,"Granívoro. Alimenta-se também de frutos, algum...",Ocorrem 2 ou 3 posturas por temporada. Põe 2 o...,"Pode ser encontrado em cerrados, caatingas, ca...","No Brasil, ocorre nos estados do Maranhão, Par...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['sementes', 'fru...","{'habitat': ['cerrado', 'caatinga', 'campo nat...","{'locomocao': '', 'sociabilidade': 'territoria..."
736,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",Predominantemente granívoro com adaptação para...,Durante a reprodução vive estritamente aos cas...,Habita mata baixa rala e bem ensolarada (caati...,Ocorre especialmente nas regiões Nordeste e Su...,"{'bico': 'Granívoro', 'asa': '', 'pata': '', '...","{'tipo': 'granívoro', 'itens': ['sementes', 'f...","{'habitat': ['caatinga', 'cerrado']}","{'locomocao': 'voadora', 'sociabilidade': '', ..."
737,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,"Frutos, costuma consumir muito o fruto da aroe...","O ninho, construído pelo casal, é compacto, fe...","Habita matas abertas, capões, matas ciliares, ...",Ocorre nas regiões tropicais e subtropicais ao...,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoe', 'mata ciliar', 'zona de ...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
738,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,"Caça insetos no meio das folhas, às vezes fica...",Possui um chamado de notas agudas e assobiadas...,"Muito ativo, vive em casais e pequenos grupos,...",Ocorre em todo o Brasil e também na América Ce...,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['insetos', 'frut...","{'habitat': ['campo natural', 'floresta aberta...","{'locomocao': 'voadora', 'sociabilidade': 'gre..."
739,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,Essa saíra se alimenta de frutos e insetos com...,"O ninho, em forma de taça aberta, é feito com ...","Habita capoeiras, matas abertas e ciliares, ár...",A espécie é dividida em dois grupos:,"{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['frutas', 'inset...","{'habitat': ['capoeira', 'área ciliar', 'área ...","{'locomocao': '', 'sociabilidade': 'gregária',..."

In [14]:
new_df['tipo_bico'] = new_df['morfologia_llm_json'].map(lambda x: x.get('bico', None))
new_df['formato_asa'] = new_df['morfologia_llm_json'].map(lambda x: x.get('asa', None))
new_df['tipo_pata'] = new_df['morfologia_llm_json'].map(lambda x: x.get('pata', None))
new_df['cores'] = new_df['morfologia_llm_json'].map(lambda x: x.get('cores', None))
new_df['tamanho'] = new_df['morfologia_llm_json'].map(lambda x: x.get('tamanho', None))
new_df.head()

/tmp/ipykernel_34113/2719038849.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tipo_bico'] = new_df['morfologia_llm_json'].map(lambda x: x.get('bico', None))
/tmp/ipykernel_34113/2719038849.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['formato_asa'] = new_df['morfologia_llm_json'].map(lambda x: x.get('asa', None))
/tmp/ipykernel_34113/2719038849.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tipo_pata'] = new_df['morfologia_llm_json'].map(lambda x: x.get('pata', None))
/tmp/ipykernel_34113/2719038849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cores'] = new_df['morfologia_llm_json'].map(lambda x: x.get('cores', None))
/tmp/ipykernel_34113/2719038849.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tamanho'] = new_df['morfologia_llm_json'].map(lambda x: x.get('tamanho', None))

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,dist_geo,morfologia_llm_json,food_llm_json,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores,tamanho
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,R (Comitê Brasileiro de Registros Ornitológico...,"{'bico': 'Generalista', 'asa': 'Elíptica', 'pa...","{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",Grande
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"Região norte, oeste da região Nordeste, Centro...","{'bico': 'Generalista', 'asa': '', 'pata': '',...","{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[],Médio
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,Ocorre em quase todo território brasileiro des...,"{'bico': 'Sondador', 'asa': '', 'pata': '', 'c...","{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]",
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Todo o Brasil até o sul do rio Amazonas e tamb...,"{'bico': 'Sondador', 'asa': '', 'pata': 'Anizo...","{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"Ocorre nas regiões norte (no Tocantins), Norde...","{'bico': '', 'asa': '', 'pata': '', 'cores': [...","{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]",Pequeno

In [15]:
new_df['caracteristica_trofica'] = new_df['food_llm_json'].map(lambda x: x.get('tipo', None))
new_df['dieta_principal'] = new_df['food_llm_json'].map(lambda x: x.get('itens', None))
new_df.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,food_llm_json,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"{'tipo': 'onívoro', 'itens': ['folhas', 'fruta...","{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ..."
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"{'tipo': 'onívoro', 'itens': ['frutas', 'molus...","{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[],Médio,onívoro,"[frutas, moluscos, insetos]"
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"{'tipo': 'onívoro', 'itens': ['sementes', 'ins...","{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]",,onívoro,"[sementes, insetos, vermes]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"{'tipo': 'onívoro', 'itens': ['insetos', 'seme...","{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onívoro,"[insetos, sementes, raízes, tubérculos, roedores]"
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"{'tipo': 'onívoro', 'itens': ['grãos', 'artróp...","{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]",Pequeno,onívoro,"[grãos, artrópodes, moluscos, frutas]"

In [16]:
new_df['habitat'] = new_df['habitat_llm_json'].map(lambda x: x.get('habitat', None))
new_df.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,habitat_llm_json,behavior_llm_json,tipo_bico,formato_asa,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"{'habitat': ['campo natural', 'cerrado', 'pamp...","{'locomocao': 'corredora', 'sociabilidade': 'g...",Generalista,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,"{'habitat': ['mata ciliar', 'cerrado']}","{'locomocao': '', 'sociabilidade': '', 'ativid...",Generalista,,,[],Médio,onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]"
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"{'habitat': ['cerrado', 'campo natural', 'plan...","{'locomocao': '', 'sociabilidade': '', 'ativid...",Sondador,,,"[marrom avermelhado, acinzentado]",,onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"{'habitat': ['campo natural', 'cerrado', 'caat...","{'locomocao': 'corredora', 'sociabilidade': 's...",Sondador,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]"
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"{'habitat': ['campo natural', 'plantação', 'ár...","{'locomocao': 'voadora', 'sociabilidade': 'gre...",,,,"[marrons, amarelo, branco]",Pequeno,onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]"

In [17]:
new_df['locomocao'] = new_df['behavior_llm_json'].map(lambda x: x.get('locomocao', None))
new_df['sociabilidade'] = new_df['behavior_llm_json'].map(lambda x: x.get('sociabilidade', None))
new_df['atividade'] = new_df['behavior_llm_json'].map(lambda x: x.get('atividade', None))
new_df.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,formato_asa,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,,,[],Médio,onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,,,"[marrom avermelhado, acinzentado]",,onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna]
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,,,"[marrons, amarelo, branco]",Pequeno,onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna]

In [18]:
new_df2 =  new_df.drop(
    [
        "morfologia_llm_json", "food_llm_json",
        "habitat_llm_json", "behavior_llm_json"
    ],
    axis= 1
) 
new_df2 = new_df2.dropna()
new_df2.head()

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,formato_asa,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Elíptica,Anizodáctilo,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]"
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,,,[],Médio,onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna]
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,,,"[marrom avermelhado, acinzentado]",,onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]"
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna]
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,,,"[marrons, amarelo, branco]",Pequeno,onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna]

In [19]:
new_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 564 entries, 0 to 739
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   taxonomia               564 non-null    object
 1   ordem                   564 non-null    object
 2   familia                 564 non-null    object
 3   subfamilia              564 non-null    object
 4   genero                  564 non-null    object
 5   especie                 564 non-null    object
 6   nome_pt                 564 non-null    object
 7   nome_eng                564 non-null    object
 8   url_wikiaves            564 non-null    object
 9   caracteristicas         564 non-null    object
 10  alimentacao             564 non-null    object
 11  reproducao              564 non-null    object
 12  habitos                 564 non-null    object
 13  dist_geo                564 non-null    object
 14  tipo_bico               564 non-null    object
 15  formato_asa             564 non-null    object
 16  tipo_pata               564 non-null    object
 17  cores                   564 non-null    object
 18  tamanho                 564 non-null    object
 19  caracteristica_trofica  564 non-null    object
 20  dieta_principal         564 non-null    object
 21  habitat                 564 non-null    object
 22  locomocao               564 non-null    object
 23  sociabilidade           564 non-null    object
 24  atividade               564 non-null    object
dtypes: object(25)
memory usage: 114.6+ KB

## Validar Tipo de Bico

In [20]:
bico_by_familly = {
    "generalista": ["Turdidae", "Thraupidae", "Mimidae"],
    "insetivoro": ["Tyrannidae", "Troglodytidae", "Furnariidae"],
    "granivoro": ["Fringillidae", "Emberizidae", "Cardinalidae"],
    "comedor de sementes de pinho": [],
    "nectarivoro": ["Trochilidae", "Meliphagidae"],
    "frugivoro": ["Ramphastidae", "Psittacidae", "Cotingidae"],
    "insetos em troncos": ["Picidae"],
    "rede de pesca": ["Sulidae"],
    "pescador de superficie": ["Laridae", "Sternidae"],
    "limicola": ["Scolopacidae", "Charadriidae"],
    "sondador": ["Recurvirostridae", "Ibidorhynchidae"],
    "filtrador": ["Phoenicopteridae", "Anatidae"],
    "pescador": ["Alcedinidae", "Anhingidae"],
    "pato mergulhador": ["Anatidae"],
    "carniceiro": ["Cathartidae"],
    "raptorial": ["Accipitridae", "Falconidae"]
}


def recap_bico_by_familly(familly: str):
    for key, values in bico_by_familly.items():
        if familly in values:
            return key
    return None

In [21]:
new_df2["tipo_bico_recap"] = new_df2["familia"].apply(recap_bico_by_familly)
new_df2["tipo_bico_recap"]

0             None
1             None
2             None
3             None
4             None
          ...
735    generalista
736    generalista
737    generalista
738    generalista
739    generalista
Name: tipo_bico_recap, Length: 564, dtype: object

In [22]:
new_df2[new_df2["tipo_bico_recap"].isna()]["familia"].unique()

array(['Rheidae', 'Tinamidae', 'Anhimidae', 'Cracidae', 'Podicipedidae',
       'Columbidae', 'Cuculidae', 'Nyctibiidae', 'Caprimulgidae',
       'Apodidae', 'Aramidae', 'Rallidae', 'Heliornithidae', 'Jacanidae',
       'Ciconiidae', 'Phalacrocoracidae', 'Ardeidae', 'Threskiornithidae',
       'Pandionidae', 'Tytonidae', 'Strigidae', 'Trogonidae', 'Momotidae',
       'Galbulidae', 'Bucconidae', 'Cariamidae', 'Thamnophilidae',
       'Dendrocolaptidae', 'Pipridae', 'Tityridae', 'Rhynchocyclidae',
       'Icteridae'], dtype=object)

In [23]:
new_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 564 entries, 0 to 739
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   taxonomia               564 non-null    object
 1   ordem                   564 non-null    object
 2   familia                 564 non-null    object
 3   subfamilia              564 non-null    object
 4   genero                  564 non-null    object
 5   especie                 564 non-null    object
 6   nome_pt                 564 non-null    object
 7   nome_eng                564 non-null    object
 8   url_wikiaves            564 non-null    object
 9   caracteristicas         564 non-null    object
 10  alimentacao             564 non-null    object
 11  reproducao              564 non-null    object
 12  habitos                 564 non-null    object
 13  dist_geo                564 non-null    object
 14  tipo_bico               564 non-null    object
 15  formato_asa             564 non-null    object
 16  tipo_pata               564 non-null    object
 17  cores                   564 non-null    object
 18  tamanho                 564 non-null    object
 19  caracteristica_trofica  564 non-null    object
 20  dieta_principal         564 non-null    object
 21  habitat                 564 non-null    object
 22  locomocao               564 non-null    object
 23  sociabilidade           564 non-null    object
 24  atividade               564 non-null    object
 25  tipo_bico_recap         383 non-null    object
dtypes: object(26)
memory usage: 119.0+ KB

In [39]:
new_df2["tipo_bico"].unique()

array(['generalista', 'sondador', None, 'filtrador', 'frugivoro',
       'granivoro', 'insetivoro', 'nectarivoro', 'insetos em troncos',
       'limicola', 'pescador', 'carniceiro', 'raptorial'], dtype=object)

In [25]:
new_df2.loc[new_df2["tipo_bico"]=='','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]==' ','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='curto','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='fim da descrição:','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='rósio','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='roseo','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='sertívoro','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='accinzentado','tipo_bico'] = None
new_df2.loc[new_df2["tipo_bico"]=='Rasteral','tipo_bico'] = None

new_df2.loc[new_df2["tipo_bico"]=='Généraliste','tipo_bico'] = 'generalista'
new_df2.loc[new_df2["tipo_bico"]=='Generalista','tipo_bico'] = 'generalista'
new_df2.loc[new_df2["tipo_bico"]=='frugívoro','tipo_bico'] = 'frugivoro'
new_df2.loc[new_df2["tipo_bico"]=='Frugívoro','tipo_bico'] = 'frugivoro'
new_df2.loc[new_df2["tipo_bico"]=='Granívoro','tipo_bico'] = 'granivoro'
new_df2.loc[new_df2["tipo_bico"]=='heterogénic (Nectarívoro) ','tipo_bico'] = 'nectarivoro'
new_df2.loc[new_df2["tipo_bico"]=='Insetívoro','tipo_bico'] = 'insetivoro'
new_df2.loc[new_df2["tipo_bico"]=='Nectarívoro','tipo_bico'] = 'nectarivoro'
new_df2.loc[new_df2["tipo_bico"]=='insetívoro','tipo_bico'] = 'insetivoro'
new_df2.loc[new_df2["tipo_bico"]=='Inserção em troncos','tipo_bico'] = 'insetos em troncos'
new_df2.loc[new_df2["tipo_bico"]=='Insetos em troncos','tipo_bico'] = 'insetos em troncos'
new_df2.loc[new_df2["tipo_bico"]=='Limícola','tipo_bico'] = 'limicola'
new_df2.loc[new_df2["tipo_bico"]=='Pescador','tipo_bico'] = 'pescador'
new_df2.loc[new_df2["tipo_bico"]=='Carniceiro','tipo_bico'] = 'carniceiro'
new_df2.loc[new_df2["tipo_bico"]=='Raptorial','tipo_bico'] = 'raptorial'
new_df2.loc[new_df2["tipo_bico"]=='Sondador','tipo_bico'] = 'sondador'
new_df2.loc[new_df2["tipo_bico"]=='Filtrador','tipo_bico'] = 'filtrador'

In [26]:
new_df2["analise_bico"] = new_df2["tipo_bico"] == new_df2["tipo_bico_recap"]
new_df2[["tipo_bico","tipo_bico_recap","analise_bico"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 564 entries, 0 to 739
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tipo_bico        439 non-null    object
 1   tipo_bico_recap  383 non-null    object
 2   analise_bico     564 non-null    bool
dtypes: bool(1), object(2)
memory usage: 13.8+ KB

In [27]:
new_df2[["familia","nome_pt","dieta_principal","tipo_bico","tipo_bico_recap","analise_bico"]]
new_df2["tipo_bico_recap"] = new_df2[["tipo_bico_recap","tipo_bico"]].apply(
    lambda row: row["tipo_bico"] if pd.isna(row["tipo_bico_recap"]) else row["tipo_bico_recap"],
    axis=1
)
new_df2

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico_recap,analise_bico
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista,False
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,[],Médio,onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna],generalista,False
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,"[marrom avermelhado, acinzentado]",,onívoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]",sondador,False
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onívoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador,False
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,"[marrons, amarelo, branco]",Pequeno,onívoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,"[azul-acinzentada, preto, acanelados, branco-a...",Pequeno,onívoro,"[sementes, frutas, insetos, flores]","[cerrado, caatinga, campo natural, área alagada]",,territorial,[diurna],generalista,True
736,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,"[vermelho, cinza, preto, branco, pardo-anegado...",Pequeno,granívoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,,[diurna],generalista,False
737,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,"[cinza, azul turquesa, cinza escuro, esverdead...",Pequeno,onívoro,"[frutas, insetos, folhas, brotos, flores]","[capoe, mata ciliar, zona de cultivo, mata deg...",voadora,gregária,[diurna],generalista,False
738,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,"[verde, amarelada]",Pequeno,onívoro,"[insetos, frutos, néctar]","[campo natural, floresta aberta, área urbana]",voadora,gregária,[diurna],generalista,False
739,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,"[amarelo-dourada, preto, amarelo]",,onívoro,"[frutas, insetos]","[capoeira, área ciliar, área urbana, plantação]",,gregária,[diurna],generalista,False

## Validar Dieta Principal e Caracteristica Trofica

In [28]:
new_df2.head(2)

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico_recap,analise_bico
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,"[cinza, preto, amarelado]",Grande,onívoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista,False
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,[],Médio,onívoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna],generalista,False

In [29]:
new_df2["caracteristica_trofica"].unique()

array(['onívoro', 'herbívoro', 'granívoro', 'frugívoro', 'granívoro ',
       'insetívoro', '', 'carnívoro', 'carnívoro-insetívoro', 'onívoros',
       'granívoro insectivor', 'omnívoro', 'insectivor'], dtype=object)

In [30]:
new_df2.loc[new_df2["caracteristica_trofica"]=='','caracteristica_trofica'] = None

new_df2.loc[new_df2["caracteristica_trofica"]=='onívoro','caracteristica_trofica'] = 'onivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='onívoros','caracteristica_trofica'] = 'onivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='omnívoro','caracteristica_trofica'] = 'onivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='granívoro','caracteristica_trofica'] = 'granivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='granívoro ','caracteristica_trofica'] = 'granivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='carnívoro','caracteristica_trofica'] = 'carnivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='insetívoro','caracteristica_trofica'] = 'insetivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='insectivor','caracteristica_trofica'] = 'insetivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='herbívoro','caracteristica_trofica'] = 'herbivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='frugívoro','caracteristica_trofica'] = 'frugivoro'

In [31]:
new_df2.loc[new_df2["caracteristica_trofica"]=='granívoro insectivor']

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico_recap,analise_bico
355,Sporophila angolensis,Passeriformes,Thraupidae,Sporophilinae,Sporophila,angolensis,curió,Chestnut-bellied Seed-Finch,https://www.wikiaves.com.br/wiki/curio,"Mede entre 10,6 e 12,4 centímetros de comprime...",...,"[preto, acinzentado, castanho, branco, pardo]",Pequeno,granívoro insectivor,"[sementes, insetos]","[floresta aberta, floresta subtropicais ou tro...",voadora,,[diurna],generalista,False

In [32]:
new_df2.loc[new_df2["caracteristica_trofica"]=='carnívoro-insetívoro','caracteristica_trofica'] = 'insetivoro'
new_df2.loc[new_df2["caracteristica_trofica"]=='granívoro insectivor','caracteristica_trofica'] = 'onívoro'

In [33]:
new_df2["atividade"].unique()

TypeError: unhashable type: 'list'

In [ ]:
lista_cores = []
for d in new_df2["cores"]:
    lista_cores.extend(d)

len(lista_cores)
len(set(lista_cores))
lista_cores

In [ ]:
from collections import Counter

lista_habitat = []
for d in new_df2["habitat"]:
    lista_habitat.extend(d)

array_habitat = np.array(lista_habitat)
c = Counter(array_habitat)
c

In [ ]:
lista_dieta = []
for d in new_df2["dieta_principal"]:
    lista_dieta.extend(d)

array_dieta = np.array(lista_dieta)
c = Counter(array_dieta)
c

## Dataframe oficial

In [34]:
df_ofc = new_df2.drop(["tipo_bico","analise_bico"], axis = 1)
df_ofc = df_ofc.rename(columns={"tipo_bico_recap":"tipo_bico"})
df_ofc

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
0,Rhea americana,Rheiformes,Rheidae,,Rhea,americana,ema,Greater Rhea,https://www.wikiaves.com.br/wiki/ema,134 – 170 cm de altura dependendo da postura a...,...,Anizodáctilo,"[cinza, preto, amarelado]",Grande,onivoro,"[folhas, frutas, sementes, insetos, moluscos, ...","[campo natural, cerrado, pampa]",corredora,gregária,"[diurna, crepuscular]",generalista
1,Crypturellus undulatus,Tinamiformes,Tinamidae,,Crypturellus,undulatus,jaó,Undulated Tinamou,https://www.wikiaves.com.br/wiki/jao,Mede cerca de 31 cm de comprimento.,...,,[],Médio,onivoro,"[frutas, moluscos, insetos]","[mata ciliar, cerrado]",,,[diurna],generalista
2,Crypturellus parvirostris,Tinamiformes,Tinamidae,,Crypturellus,parvirostris,inhambu-chororó,Small-billed Tinamou,https://www.wikiaves.com.br/wiki/inhambu-chororo,"Muito semelhante ao inhambu-chintã, possui o c...",...,,"[marrom avermelhado, acinzentado]",,onivoro,"[sementes, insetos, vermes]","[cerrado, campo natural, plantação, pastagem]",,,"[diurna, crepuscular]",sondador
3,Rhynchotus rufescens,Tinamiformes,Tinamidae,,Rhynchotus,rufescens,perdiz,Red-winged Tinamou,https://www.wikiaves.com.br/wiki/perdiz,Mede entre 38 e 42 centímetros de comprimento....,...,Anizodáctilo,"[preto, bege, marrom escuro, canela, castanho ...",Médio,onivoro,"[insetos, sementes, raízes, tubérculos, roedores]","[campo natural, cerrado, caatinga]",corredora,solitária,[diurna],sondador
4,Nothura maculosa,Tinamiformes,Tinamidae,,Nothura,maculosa,codorna-amarela,Spotted Nothura,https://www.wikiaves.com.br/wiki/codorna-amarela,Tem cerca de 23 centímetros e pesa aproximadam...,...,,"[marrons, amarelo, branco]",Pequeno,onivoro,"[grãos, artrópodes, moluscos, frutas]","[campo natural, plantação, área urbana]",voadora,gregária,[diurna],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,,"[azul-acinzentada, preto, acanelados, branco-a...",Pequeno,onivoro,"[sementes, frutas, insetos, flores]","[cerrado, caatinga, campo natural, área alagada]",,territorial,[diurna],generalista
736,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,,"[vermelho, cinza, preto, branco, pardo-anegado...",Pequeno,granivoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,,[diurna],generalista
737,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,,"[cinza, azul turquesa, cinza escuro, esverdead...",Pequeno,onivoro,"[frutas, insetos, folhas, brotos, flores]","[capoe, mata ciliar, zona de cultivo, mata deg...",voadora,gregária,[diurna],generalista
738,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,,"[verde, amarelada]",Pequeno,onivoro,"[insetos, frutos, néctar]","[campo natural, floresta aberta, área urbana]",voadora,gregária,[diurna],generalista
739,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,,"[amarelo-dourada, preto, amarelo]",,onivoro,"[frutas, insetos]","[capoeira, área ciliar, área urbana, plantação]",,gregária,[diurna],generalista

In [35]:
df_ofc[df_ofc.duplicated(subset=["especie"])]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
14,Tachybaptus dominicus,Podicipediformes,Podicipedidae,,Tachybaptus,dominicus,mergulhão-pequeno,Least Grebe,https://www.wikiaves.com.br/wiki/mergulhao-peq...,"Mede de 21 a 26 cm, pesando de 130 a 180 g. Me...",...,,"[pardo-acinzentada, preto, branco, amarelo-claro]",Médio,onivoro,"[peixes, algas, anfíbios]","[área alagada, lagos isolados]",voadora,gregária,[diurna],None
67,Mustelirallus albicollis,Gruiformes,Rallidae,,Mustelirallus,albicollis,sanã-carijó,Ash-throated Crake,https://www.wikiaves.com.br/wiki/sana-carijo,Mede entre 21 e 24 centímetros de comprimento ...,...,,"[negro, pardacentas, esverdeadas]",Pequeno,onivoro,"[brotos de milho, cobras-d´água, insetos, larvas]","[área alagada, pantanal]",,,[],None
80,Mycteria americana,Ciconiiformes,Ciconiidae,,Mycteria,americana,cabeça-seca,Wood Stork,https://www.wikiaves.com.br/wiki/cabeca-seca,Mede entre 86 e 100 cm de comprimento e pesa e...,...,,[],Grande,onivoro,"[peixes, rãs, insetos]","[pantanal, manguezais, área alagada]",voadora,gregária,[diurna],pescador
92,Mesembrinibis cayennensis,Pelecaniformes,Threskiornithidae,,Mesembrinibis,cayennensis,coró-coró,Green Ibis,https://www.wikiaves.com.br/wiki/coro-coro,Adulto mede entre 48 e 56 centímetros de compr...,...,,"[escura, verde bronzeada, azul metálico, verde...",Médio,onivoro,"[invertebrados, plantas aquáticas]","[mata ciliar, área urbana]",voadora,gregária,[diurna],nectarivoro
107,Busarellus nigricollis,Accipitriformes,Accipitridae,Accipitrininae,Busarellus,nigricollis,gavião-belo,Black-collared Hawk,https://www.wikiaves.com.br/wiki/gaviao-belo,O gavião-belo mede entre 46 e 53 centímetros d...,...,,"[branco, marrom escuro, laranja-marrom, preto,...",Médio,carnivoro,"[insetos, peixes, caramujos]","[beira de lagos, banhados, pantanals, campos i...",voadora,,[diurna],raptorial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Schistochlamys ruficapillus,Passeriformes,Thraupidae,Thraupinae,Schistochlamys,ruficapillus,bico-de-veludo,Cinnamon Tanager,https://www.wikiaves.com.br/wiki/bico-de-veludo,Mede cerca de 18 centímetros de comprimento e ...,...,,"[azul-acinzentada, preto, acanelados, branco-a...",Pequeno,onivoro,"[sementes, frutas, insetos, flores]","[cerrado, caatinga, campo natural, área alagada]",,territorial,[diurna],generalista
736,Paroaria dominicana,Passeriformes,Thraupidae,Thraupinae,Paroaria,dominicana,cardeal-do-nordeste,Red-cowled Cardinal,https://www.wikiaves.com.br/wiki/cardeal-do-no...,"Mede cerca de 17,2 centímetros. Plumagem de ca...",...,,"[vermelho, cinza, preto, branco, pardo-anegado...",Pequeno,granivoro,"[sementes, frutas]","[caatinga, cerrado]",voadora,,[diurna],generalista
737,Thraupis sayaca,Passeriformes,Thraupidae,Thraupinae,Thraupis,sayaca,sanhaço-cinzento,Sayaca Tanager,https://www.wikiaves.com.br/wiki/sanhaco-cinzento,Mede entre 16 e 19 centímetros de comprimento ...,...,,"[cinza, azul turquesa, cinza escuro, esverdead...",Pequeno,onivoro,"[frutas, insetos, folhas, brotos, flores]","[capoe, mata ciliar, zona de cultivo, mata deg...",voadora,gregária,[diurna],generalista
738,Thraupis palmarum,Passeriformes,Thraupidae,Thraupinae,Thraupis,palmarum,sanhaço-do-coqueiro,Palm Tanager,https://www.wikiaves.com.br/wiki/sanhaco-do-co...,Mede entre 17 e 18 centímetros de comprimento ...,...,,"[verde, amarelada]",Pequeno,onivoro,"[insetos, frutos, néctar]","[campo natural, floresta aberta, área urbana]",voadora,gregária,[diurna],generalista
739,Stilpnia cayana,Passeriformes,Thraupidae,Thraupinae,Stilpnia,cayana,saíra-amarela,Burnished-buff Tanager,https://www.wikiaves.com.br/wiki/saira-amarela,O macho possui uma plumagem de coloração amare...,...,,"[amarelo-dourada, preto, amarelo]",,onivoro,"[frutas, insetos]","[capoeira, área ciliar, área urbana, plantação]",,gregária,[diurna],generalista

In [36]:
df_ofc = df_ofc.drop_duplicates(subset=["especie"])

In [37]:
df_ofc[df_ofc["nome_pt"]=="bem-te-vi"]

,taxonomia,ordem,familia,subfamilia,genero,especie,nome_pt,nome_eng,url_wikiaves,caracteristicas,...,tipo_pata,cores,tamanho,caracteristica_trofica,dieta_principal,habitat,locomocao,sociabilidade,atividade,tipo_bico
245,Pitangus sulphuratus,Passeriformes,Tyrannidae,Tyranninae,Pitangus,sulphuratus,bem-te-vi,Great Kiskadee,https://www.wikiaves.com.br/wiki/bem-te-vi,"Ave de médio porte, o bem-te-vi ou bem-te-vi v...",...,,"[pardo, amarelo, branco, preto]",Médio,onivoro,"[insetos, frutas, ovos, roedores, peixes, giri...","[área urbana, mata ciliar, área alagada]",,territorial,[diurna],insetivoro

In [38]:
df_ofc.to_json("../data/oficial/parameterized_dataset_udi.json", orient="records")